export type ChordDetailSeoCopy = {
  title: string;
  description: string;
  h1?: string;
  h2?: Record<string, string>;
  intro?: string;
  theory?: string;
  fingering?: string;
  keyboardHelp?: string;
  faq?: { q: string; a: string }[];
};

/** Task 11 same-entity labels. Does not change pack music names, notes, or URLs. */
export const CHORD_DETAIL_SEO_COPY: Record<string, ChordDetailSeoCopy> = {
  "/chords/a-7": {
    title: "A7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "A7 Chord",
    description: "Learn the A7 chord on piano: A, C♯, E and G. See the keyboard diagram and three inversions, hear the notes, and download a printable reference.",
    intro: "A7, also called A dominant seventh, contains A, C♯, E and G. Use the piano diagram to find the notes and compare root position with three inversions.",
    theory: "The A7 chord combines a major triad with a minor seventh.",
    fingering: "Finger numbers are not included. The diagrams show note positions, not a prescribed hand shape.",
    h2: {
      "A Dominant Seventh Piano Chord": "A7 Chord",
      "A Dominant Seventh keyboard and inversions": "A7 Piano Notes and Keyboard Diagram",
      "A Dominant Seventh formula": "How the A7 Chord Is Built",
      "A Dominant Seventh positions and inversions": "A7 Chord Inversions",
      "Chord & positions": "A7 Piano Notes and Keyboard Diagram",
      "Compare A Dominant Seventh": "A7 Compared with A Major",
      "Questions about A7": "Questions About A7",
      "Build A7 on the keyboard": "Build A7 on the Keyboard",
      "Print this chord reference": "Print the A7 Chord Reference",
      "Related chord references": "Related Chords and Practice",
    },
  },
  "/chords/a-flat-7": {
    title: "A♭7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "A♭7 Chord",
    description: "Learn the A♭7 chord on piano: A♭, C, E♭ and G♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "A♭7, also called A♭ dominant seventh, contains A♭, C, E♭ and G♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A♭ Dominant Seventh Piano Chord": "A♭7 Chord",
      "A♭ Dominant Seventh keyboard and inversions": "A♭7 piano notes and keyboard diagram",
      "A♭ Dominant Seventh formula": "How is the A♭7 chord built?",
      "A♭ Dominant Seventh positions and inversions": "A♭7 inversions",
      "Chord & positions": "A♭7 piano notes and keyboard diagram",
    },
  },
  "/chords/a-flat-m7": {
    title: "A♭m7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "A♭m7 Chord",
    description: "Learn the A♭m7 chord on piano: A♭, C♭, E♭ and G♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "A♭m7, also called A♭ minor seventh, contains A♭, C♭, E♭ and G♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A♭ Minor Seventh Piano Chord": "A♭m7 Chord",
      "A♭ Minor Seventh keyboard and inversions": "A♭m7 piano notes and keyboard diagram",
      "A♭ Minor Seventh formula": "How is the A♭m7 chord built?",
      "A♭ Minor Seventh positions and inversions": "A♭m7 inversions",
      "Chord & positions": "A♭m7 piano notes and keyboard diagram",
    },
  },
  "/chords/a-flat-m7-flat5": {
    title: "A♭ Half-Diminished Chord (A♭m7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "A♭ Half-Diminished Chord (A♭m7♭5)",
    description: "Learn the A♭ Half-Diminished Chord (A♭m7♭5) on piano: A♭, C♭, E𝄫 and G♭. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "A♭ Half-Diminished Chord (A♭m7♭5) contains A♭, C♭, E𝄫 and G♭. The compact symbol A♭m7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A♭ Half-Diminished Seventh Piano Chord": "A♭ Half-Diminished Chord (A♭m7♭5)",
      "A♭ Half-Diminished Seventh keyboard and inversions": "A♭m7♭5 piano notes and keyboard diagram",
      "A♭ Half-Diminished Seventh formula": "How is the A♭m7♭5 chord built?",
      "A♭ Half-Diminished Seventh positions and inversions": "A♭m7♭5 inversions",
      "Chord & positions": "A♭m7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/a-flat-maj7": {
    title: "A♭maj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "A♭maj7 Chord",
    description: "Learn the A♭maj7 chord on piano: A♭, C, E♭ and G. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "A♭maj7, also called A♭ major seventh, contains A♭, C, E♭ and G. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A♭ Major Seventh Piano Chord": "A♭maj7 Chord",
      "A♭ Major Seventh keyboard and inversions": "A♭maj7 piano notes and keyboard diagram",
      "A♭ Major Seventh formula": "How is the A♭maj7 chord built?",
      "A♭ Major Seventh positions and inversions": "A♭maj7 inversions",
      "Chord & positions": "A♭maj7 piano notes and keyboard diagram",
    },
  },
  "/chords/a-flat-sus2": {
    title: "A♭sus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "A♭sus2 Chord",
    description: "Learn the A♭sus2 chord on piano: A♭, B♭ and E♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "A♭sus2, also called A♭ suspended second, contains A♭, B♭ and E♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A♭ Suspended 2nd Piano Chord": "A♭sus2 Chord",
      "A♭ Suspended 2nd keyboard and inversions": "A♭sus2 piano notes and keyboard diagram",
      "A♭ Suspended 2nd formula": "How is the A♭sus2 chord built?",
      "A♭ Suspended 2nd inversions": "A♭sus2 inversions",
      "Chord & positions": "A♭sus2 piano notes and keyboard diagram",
    },
  },
  "/chords/a-flat-sus4": {
    title: "A♭sus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "A♭sus4 Chord",
    description: "Learn the A♭sus4 chord on piano: A♭, D♭ and E♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "A♭sus4, also called A♭ suspended fourth, contains A♭, D♭ and E♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A♭ Suspended 4th Piano Chord": "A♭sus4 Chord",
      "A♭ Suspended 4th keyboard and inversions": "A♭sus4 piano notes and keyboard diagram",
      "A♭ Suspended 4th formula": "How is the A♭sus4 chord built?",
      "A♭ Suspended 4th inversions": "A♭sus4 inversions",
      "Chord & positions": "A♭sus4 piano notes and keyboard diagram",
    },
  },
  "/chords/a-m7": {
    title: "Am7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Am7 Chord",
    description: "Learn the Am7 chord on piano: A, C, E and G. See the keyboard diagram and three inversions, hear the chord, practice the notes, and download a printable reference.",
    intro: "Am7, also called A minor seventh, contains A–C–E–G and uses the formula 1–♭3–5–♭7.",
    theory: "Am7 is a minor triad plus a minor seventh.",
    fingering: "Fingering is not included on this page. The diagrams show note positions, not a required hand shape.",
    h2: {
      "A Minor Seventh Piano Chord": "Am7 Chord",
      "A Minor Seventh keyboard and inversions": "Am7 piano notes and keyboard diagram",
      "A Minor Seventh formula": "How is the Am7 chord built?",
      "A Minor Seventh positions and inversions": "Am7 inversions",
      "Chord & positions": "Am7 piano notes and keyboard diagram",
    },
  },
  "/chords/a-m7-flat5": {
    title: "A Half-Diminished Chord (Am7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "A Half-Diminished Chord (Am7♭5)",
    description: "Learn the A Half-Diminished Chord (Am7♭5) on piano: A, C, E♭ and G. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "A Half-Diminished Chord (Am7♭5) contains A, C, E♭ and G. The compact symbol Am7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A Half-Diminished Seventh Piano Chord": "A Half-Diminished Chord (Am7♭5)",
      "A Half-Diminished Seventh keyboard and inversions": "Am7♭5 piano notes and keyboard diagram",
      "A Half-Diminished Seventh formula": "How is the Am7♭5 chord built?",
      "A Half-Diminished Seventh positions and inversions": "Am7♭5 inversions",
      "Chord & positions": "Am7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/a-maj7": {
    title: "Amaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Amaj7 Chord",
    description: "Learn the Amaj7 chord on piano: A, C♯, E and G♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Amaj7, also called A major seventh, contains A, C♯, E and G♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Amaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A Major Seventh Piano Chord": "Amaj7 Chord",
      "A Major Seventh keyboard and inversions": "Amaj7 piano notes and keyboard diagram",
      "A Major Seventh formula": "How is the Amaj7 chord built?",
      "A Major Seventh positions and inversions": "Amaj7 inversions",
      "Chord & positions": "Amaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/a-sus2": {
    title: "Asus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Asus2 Chord",
    description: "Learn the Asus2 chord on piano: A, B and E. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Asus2, also called A suspended second, contains A, B and E. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A Suspended 2nd Piano Chord": "Asus2 Chord",
      "A Suspended 2nd keyboard and inversions": "Asus2 piano notes and keyboard diagram",
      "A Suspended 2nd formula": "How is the Asus2 chord built?",
      "A Suspended 2nd inversions": "Asus2 inversions",
      "Chord & positions": "Asus2 piano notes and keyboard diagram",
    },
  },
  "/chords/a-sus4": {
    title: "Asus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Asus4 Chord",
    description: "Learn the Asus4 chord on piano: A, D and E. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Asus4, also called A suspended fourth, contains A, D and E. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "A Suspended 4th Piano Chord": "Asus4 Chord",
      "A Suspended 4th keyboard and inversions": "Asus4 piano notes and keyboard diagram",
      "A Suspended 4th formula": "How is the Asus4 chord built?",
      "A Suspended 4th inversions": "Asus4 inversions",
      "Chord & positions": "Asus4 piano notes and keyboard diagram",
    },
  },
  "/chords/b-7": {
    title: "B7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "B7 Chord",
    description: "Learn the B7 chord on piano: B, D♯, F♯ and A. See the keyboard diagram and three inversions, hear the notes, and download a printable reference.",
    intro: "B7, also called B dominant seventh, contains B, D♯, F♯ and A. Use the piano diagram to find the notes and compare root position with three inversions.",
    theory: "The B7 chord combines a major triad with a minor seventh.",
    fingering: "Finger numbers are not included. The diagrams show note positions, not a prescribed hand shape.",
    keyboardHelp: "For root position, play B, D♯, F♯ and A from low to high. Switch positions to compare inversions, or play the notes one at a time.",
    h2: {
      "B Dominant Seventh Piano Chord": "B7 Chord",
      "B Dominant Seventh keyboard and inversions": "B7 Piano Notes and Keyboard Diagram",
      "B Dominant Seventh formula": "How the B7 Chord Is Built",
      "B Dominant Seventh positions and inversions": "B7 Chord Inversions",
      "Chord & positions": "B7 Piano Notes and Keyboard Diagram",
      "Compare B Dominant Seventh": "B7 Compared with B Major",
      "Questions about B7": "Questions About B7",
      "Build B7 on the keyboard": "Build B7 on the Keyboard",
      "Print this chord reference": "Print the B7 Chord Reference",
      "Related chord references": "Related Chords and Practice",
    },
    faq: [
      { q: "What is a B7 chord?", a: "B7 is a B dominant seventh chord, made up of B, D♯, F♯ and A." },
      { q: "What is the formula for B7?", a: "1–3–5–♭7." },
      { q: "How many inversions does a seventh chord have?", a: "Three inversions, in addition to root position." },
    ],
  },
  "/chords/b-flat-7": {
    title: "B♭7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "B♭7 Chord",
    description: "Learn the B♭7 chord on piano: B♭, D, F and A♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "B♭7, also called B♭ dominant seventh, contains B♭, D, F and A♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B♭ Dominant Seventh Piano Chord": "B♭7 Chord",
      "B♭ Dominant Seventh keyboard and inversions": "B♭7 piano notes and keyboard diagram",
      "B♭ Dominant Seventh formula": "How is the B♭7 chord built?",
      "B♭ Dominant Seventh positions and inversions": "B♭7 inversions",
      "Chord & positions": "B♭7 piano notes and keyboard diagram",
    },
  },
  "/chords/b-flat-m7": {
    title: "B♭m7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "B♭m7 Chord",
    description: "Learn the B♭m7 chord on piano: B♭, D♭, F and A♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "B♭m7, also called B♭ minor seventh, contains B♭, D♭, F and A♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B♭ Minor Seventh Piano Chord": "B♭m7 Chord",
      "B♭ Minor Seventh keyboard and inversions": "B♭m7 piano notes and keyboard diagram",
      "B♭ Minor Seventh formula": "How is the B♭m7 chord built?",
      "B♭ Minor Seventh positions and inversions": "B♭m7 inversions",
      "Chord & positions": "B♭m7 piano notes and keyboard diagram",
    },
  },
  "/chords/b-flat-m7-flat5": {
    title: "B♭ Half-Diminished Chord (B♭m7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "B♭ Half-Diminished Chord (B♭m7♭5)",
    description: "Learn the B♭ Half-Diminished Chord (B♭m7♭5) on piano: B♭, D♭, F♭ and A♭. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "B♭ Half-Diminished Chord (B♭m7♭5) contains B♭, D♭, F♭ and A♭. The compact symbol B♭m7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B♭ Half-Diminished Seventh Piano Chord": "B♭ Half-Diminished Chord (B♭m7♭5)",
      "B♭ Half-Diminished Seventh keyboard and inversions": "B♭m7♭5 piano notes and keyboard diagram",
      "B♭ Half-Diminished Seventh formula": "How is the B♭m7♭5 chord built?",
      "B♭ Half-Diminished Seventh positions and inversions": "B♭m7♭5 inversions",
      "Chord & positions": "B♭m7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/b-flat-maj7": {
    title: "B♭maj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "B♭maj7 Chord",
    description: "Learn the B♭maj7 chord on piano: B♭, D, F and A. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "B♭maj7, also called B♭ major seventh, contains B♭, D, F and A. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B♭ Major Seventh Piano Chord": "B♭maj7 Chord",
      "B♭ Major Seventh keyboard and inversions": "B♭maj7 piano notes and keyboard diagram",
      "B♭ Major Seventh formula": "How is the B♭maj7 chord built?",
      "B♭ Major Seventh positions and inversions": "B♭maj7 inversions",
      "Chord & positions": "B♭maj7 piano notes and keyboard diagram",
    },
  },
  "/chords/b-flat-sus2": {
    title: "B♭sus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "B♭sus2 Chord",
    description: "Learn the B♭sus2 chord on piano: B♭, C and F. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "B♭sus2, also called B♭ suspended second, contains B♭, C and F. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B♭ Suspended 2nd Piano Chord": "B♭sus2 Chord",
      "B♭ Suspended 2nd keyboard and inversions": "B♭sus2 piano notes and keyboard diagram",
      "B♭ Suspended 2nd formula": "How is the B♭sus2 chord built?",
      "B♭ Suspended 2nd inversions": "B♭sus2 inversions",
      "Chord & positions": "B♭sus2 piano notes and keyboard diagram",
    },
  },
  "/chords/b-flat-sus4": {
    title: "B♭sus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "B♭sus4 Chord",
    description: "Learn the B♭sus4 chord on piano: B♭, E♭ and F. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "B♭sus4, also called B♭ suspended fourth, contains B♭, E♭ and F. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B♭ Suspended 4th Piano Chord": "B♭sus4 Chord",
      "B♭ Suspended 4th keyboard and inversions": "B♭sus4 piano notes and keyboard diagram",
      "B♭ Suspended 4th formula": "How is the B♭sus4 chord built?",
      "B♭ Suspended 4th inversions": "B♭sus4 inversions",
      "Chord & positions": "B♭sus4 piano notes and keyboard diagram",
    },
  },
  "/chords/b-m7": {
    title: "Bm7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Bm7 Chord",
    description: "Learn the Bm7 chord on piano: B, D, F♯ and A. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Bm7, also called B minor seventh, contains B, D, F♯ and A. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Bm7 chord is a minor triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B Minor Seventh Piano Chord": "Bm7 Chord",
      "B Minor Seventh keyboard and inversions": "Bm7 piano notes and keyboard diagram",
      "B Minor Seventh formula": "How is the Bm7 chord built?",
      "B Minor Seventh positions and inversions": "Bm7 inversions",
      "Chord & positions": "Bm7 piano notes and keyboard diagram",
    },
  },
  "/chords/b-m7-flat5": {
    title: "B Half-Diminished Chord (Bm7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "B Half-Diminished Chord (Bm7♭5)",
    description: "Learn the B Half-Diminished Chord (Bm7♭5) on piano: B, D, F and A. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "B Half-Diminished Chord (Bm7♭5) contains B, D, F and A. The compact symbol Bm7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B Half-Diminished Seventh Piano Chord": "B Half-Diminished Chord (Bm7♭5)",
      "B Half-Diminished Seventh keyboard and inversions": "Bm7♭5 piano notes and keyboard diagram",
      "B Half-Diminished Seventh formula": "How is the Bm7♭5 chord built?",
      "B Half-Diminished Seventh positions and inversions": "Bm7♭5 inversions",
      "Chord & positions": "Bm7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/b-maj7": {
    title: "Bmaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Bmaj7 Chord",
    description: "Learn the Bmaj7 chord on piano: B, D♯, F♯ and A♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Bmaj7, also called B major seventh, contains B, D♯, F♯ and A♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Bmaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B Major Seventh Piano Chord": "Bmaj7 Chord",
      "B Major Seventh keyboard and inversions": "Bmaj7 piano notes and keyboard diagram",
      "B Major Seventh formula": "How is the Bmaj7 chord built?",
      "B Major Seventh positions and inversions": "Bmaj7 inversions",
      "Chord & positions": "Bmaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/b-sus2": {
    title: "Bsus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Bsus2 Chord",
    description: "Learn the Bsus2 chord on piano: B, C♯ and F♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Bsus2, also called B suspended second, contains B, C♯ and F♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B Suspended 2nd Piano Chord": "Bsus2 Chord",
      "B Suspended 2nd keyboard and inversions": "Bsus2 piano notes and keyboard diagram",
      "B Suspended 2nd formula": "How is the Bsus2 chord built?",
      "B Suspended 2nd inversions": "Bsus2 inversions",
      "Chord & positions": "Bsus2 piano notes and keyboard diagram",
    },
  },
  "/chords/b-sus4": {
    title: "Bsus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Bsus4 Chord",
    description: "Learn the Bsus4 chord on piano: B, E and F♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Bsus4, also called B suspended fourth, contains B, E and F♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "B Suspended 4th Piano Chord": "Bsus4 Chord",
      "B Suspended 4th keyboard and inversions": "Bsus4 piano notes and keyboard diagram",
      "B Suspended 4th formula": "How is the Bsus4 chord built?",
      "B Suspended 4th inversions": "Bsus4 inversions",
      "Chord & positions": "Bsus4 piano notes and keyboard diagram",
    },
  },
  "/chords/c-7": {
    title: "C7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "C7 Chord",
    description: "Learn the C7 chord on piano: C, E, G and B♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "C7, also called C dominant seventh, contains C, E, G and B♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The C7 chord is a major triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "C Dominant Seventh Piano Chord": "C7 Chord",
      "C Dominant Seventh keyboard and inversions": "C7 piano notes and keyboard diagram",
      "C Dominant Seventh formula": "How is the C7 chord built?",
      "C Dominant Seventh positions and inversions": "C7 inversions",
      "Chord & positions": "C7 piano notes and keyboard diagram",
    },
  },
  "/chords/c-m7": {
    title: "Cm7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Cm7 Chord",
    description: "Learn the Cm7 chord on piano: C, E♭, G and B♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Cm7, also called C minor seventh, contains C, E♭, G and B♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Cm7 chord is a minor triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "C Minor Seventh Piano Chord": "Cm7 Chord",
      "C Minor Seventh keyboard and inversions": "Cm7 piano notes and keyboard diagram",
      "C Minor Seventh formula": "How is the Cm7 chord built?",
      "C Minor Seventh positions and inversions": "Cm7 inversions",
      "Chord & positions": "Cm7 piano notes and keyboard diagram",
    },
  },
  "/chords/c-m7-flat5": {
    title: "C Half-Diminished Chord (Cm7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "C Half-Diminished Chord (Cm7♭5)",
    description: "Learn the C Half-Diminished Chord (Cm7♭5) on piano: C, E♭, G♭ and B♭. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "C Half-Diminished Chord (Cm7♭5) contains C, E♭, G♭ and B♭. The compact symbol Cm7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "C Half-Diminished Seventh Piano Chord": "C Half-Diminished Chord (Cm7♭5)",
      "C Half-Diminished Seventh keyboard and inversions": "Cm7♭5 piano notes and keyboard diagram",
      "C Half-Diminished Seventh formula": "How is the Cm7♭5 chord built?",
      "C Half-Diminished Seventh positions and inversions": "Cm7♭5 inversions",
      "Chord & positions": "Cm7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/c-maj7": {
    title: "Cmaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Cmaj7 Chord",
    description: "Learn the Cmaj7 chord on piano: C, E, G and B. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Cmaj7, also called C major seventh, contains C, E, G and B. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Cmaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "C Major Seventh Piano Chord": "Cmaj7 Chord",
      "C Major Seventh keyboard and inversions": "Cmaj7 piano notes and keyboard diagram",
      "C Major Seventh formula": "How is the Cmaj7 chord built?",
      "C Major Seventh positions and inversions": "Cmaj7 inversions",
      "Chord & positions": "Cmaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/c-sus2": {
    title: "Csus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Csus2 Chord",
    description: "Learn the Csus2 chord on piano: C, D and G. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Csus2, also called C suspended second, contains C, D and G. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "C Suspended 2nd Piano Chord": "Csus2 Chord",
      "C Suspended 2nd keyboard and inversions": "Csus2 piano notes and keyboard diagram",
      "C Suspended 2nd formula": "How is the Csus2 chord built?",
      "C Suspended 2nd inversions": "Csus2 inversions",
      "Chord & positions": "Csus2 piano notes and keyboard diagram",
    },
  },
  "/chords/c-sus4": {
    title: "Csus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Csus4 Chord",
    description: "Learn the Csus4 chord on piano: C, F and G. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Csus4, also called C suspended fourth, contains C, F and G. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "C Suspended 4th Piano Chord": "Csus4 Chord",
      "C Suspended 4th keyboard and inversions": "Csus4 piano notes and keyboard diagram",
      "C Suspended 4th formula": "How is the Csus4 chord built?",
      "C Suspended 4th inversions": "Csus4 inversions",
      "Chord & positions": "Csus4 piano notes and keyboard diagram",
    },
  },
  "/chords/d-7": {
    title: "D7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "D7 Chord",
    description: "Learn the D7 chord on piano: D, F♯, A and C. See the keyboard diagram and three inversions, hear the notes, and download a printable reference.",
    intro: "D7, also called D dominant seventh, contains D, F♯, A and C. Use the piano diagram to find the notes and compare root position with three inversions.",
    theory: "The D7 chord combines a major triad with a minor seventh.",
    fingering: "Finger numbers are not included. The diagrams show note positions, not a prescribed hand shape.",
    h2: {
      "D Dominant Seventh Piano Chord": "D7 Chord",
      "D Dominant Seventh keyboard and inversions": "D7 Piano Notes and Keyboard Diagram",
      "D Dominant Seventh formula": "How the D7 Chord Is Built",
      "D Dominant Seventh positions and inversions": "D7 Chord Inversions",
      "Chord & positions": "D7 Piano Notes and Keyboard Diagram",
      "Compare D Dominant Seventh": "D7 Compared with D Major",
      "Questions about D7": "Questions About D7",
      "Build D7 on the keyboard": "Build D7 on the Keyboard",
      "Print this chord reference": "Print the D7 Chord Reference",
      "Related chord references": "Related Chords and Practice",
    },
  },
  "/chords/d-flat-7": {
    title: "D♭7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "D♭7 Chord",
    description: "Learn the D♭7 chord on piano: D♭, F, A♭ and C♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "D♭7, also called D♭ dominant seventh, contains D♭, F, A♭ and C♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D♭ Dominant Seventh Piano Chord": "D♭7 Chord",
      "D♭ Dominant Seventh keyboard and inversions": "D♭7 piano notes and keyboard diagram",
      "D♭ Dominant Seventh formula": "How is the D♭7 chord built?",
      "D♭ Dominant Seventh positions and inversions": "D♭7 inversions",
      "Chord & positions": "D♭7 piano notes and keyboard diagram",
    },
  },
  "/chords/d-flat-m7": {
    title: "D♭m7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "D♭m7 Chord",
    description: "Learn the D♭m7 chord on piano: D♭, F♭, A♭ and C♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "D♭m7, also called D♭ minor seventh, contains D♭, F♭, A♭ and C♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D♭ Minor Seventh Piano Chord": "D♭m7 Chord",
      "D♭ Minor Seventh keyboard and inversions": "D♭m7 piano notes and keyboard diagram",
      "D♭ Minor Seventh formula": "How is the D♭m7 chord built?",
      "D♭ Minor Seventh positions and inversions": "D♭m7 inversions",
      "Chord & positions": "D♭m7 piano notes and keyboard diagram",
    },
  },
  "/chords/d-flat-maj7": {
    title: "D♭maj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "D♭maj7 Chord",
    description: "Learn the D♭maj7 chord on piano: D♭, F, A♭ and C. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "D♭maj7, also called D♭ major seventh, contains D♭, F, A♭ and C. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D♭ Major Seventh Piano Chord": "D♭maj7 Chord",
      "D♭ Major Seventh keyboard and inversions": "D♭maj7 piano notes and keyboard diagram",
      "D♭ Major Seventh formula": "How is the D♭maj7 chord built?",
      "D♭ Major Seventh positions and inversions": "D♭maj7 inversions",
      "Chord & positions": "D♭maj7 piano notes and keyboard diagram",
    },
  },
  "/chords/d-flat-sus2": {
    title: "D♭sus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "D♭sus2 Chord",
    description: "Learn the D♭sus2 chord on piano: D♭, E♭ and A♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "D♭sus2, also called D♭ suspended second, contains D♭, E♭ and A♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D♭ Suspended 2nd Piano Chord": "D♭sus2 Chord",
      "D♭ Suspended 2nd keyboard and inversions": "D♭sus2 piano notes and keyboard diagram",
      "D♭ Suspended 2nd formula": "How is the D♭sus2 chord built?",
      "D♭ Suspended 2nd inversions": "D♭sus2 inversions",
      "Chord & positions": "D♭sus2 piano notes and keyboard diagram",
    },
  },
  "/chords/d-flat-sus4": {
    title: "D♭sus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "D♭sus4 Chord",
    description: "Learn the D♭sus4 chord on piano: D♭, G♭ and A♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "D♭sus4, also called D♭ suspended fourth, contains D♭, G♭ and A♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D♭ Suspended 4th Piano Chord": "D♭sus4 Chord",
      "D♭ Suspended 4th keyboard and inversions": "D♭sus4 piano notes and keyboard diagram",
      "D♭ Suspended 4th formula": "How is the D♭sus4 chord built?",
      "D♭ Suspended 4th inversions": "D♭sus4 inversions",
      "Chord & positions": "D♭sus4 piano notes and keyboard diagram",
    },
  },
  "/chords/d-m7": {
    title: "Dm7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Dm7 Chord",
    description: "Learn the Dm7 chord on piano: D, F, A and C. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Dm7, also called D minor seventh, contains D, F, A and C. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Dm7 chord is a minor triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D Minor Seventh Piano Chord": "Dm7 Chord",
      "D Minor Seventh keyboard and inversions": "Dm7 piano notes and keyboard diagram",
      "D Minor Seventh formula": "How is the Dm7 chord built?",
      "D Minor Seventh positions and inversions": "Dm7 inversions",
      "Chord & positions": "Dm7 piano notes and keyboard diagram",
    },
  },
  "/chords/d-m7-flat5": {
    title: "D Half-Diminished Chord (Dm7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "D Half-Diminished Chord (Dm7♭5)",
    description: "Learn the D Half-Diminished Chord (Dm7♭5) on piano: D, F, A♭ and C. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "D Half-Diminished Chord (Dm7♭5) contains D, F, A♭ and C. The compact symbol Dm7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D Half-Diminished Seventh Piano Chord": "D Half-Diminished Chord (Dm7♭5)",
      "D Half-Diminished Seventh keyboard and inversions": "Dm7♭5 piano notes and keyboard diagram",
      "D Half-Diminished Seventh formula": "How is the Dm7♭5 chord built?",
      "D Half-Diminished Seventh positions and inversions": "Dm7♭5 inversions",
      "Chord & positions": "Dm7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/d-maj7": {
    title: "Dmaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Dmaj7 Chord",
    description: "Learn the Dmaj7 chord on piano: D, F♯, A and C♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Dmaj7, also called D major seventh, contains D, F♯, A and C♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Dmaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D Major Seventh Piano Chord": "Dmaj7 Chord",
      "D Major Seventh keyboard and inversions": "Dmaj7 piano notes and keyboard diagram",
      "D Major Seventh formula": "How is the Dmaj7 chord built?",
      "D Major Seventh positions and inversions": "Dmaj7 inversions",
      "Chord & positions": "Dmaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/d-sus2": {
    title: "Dsus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Dsus2 Chord",
    description: "Learn the Dsus2 chord on piano: D, E and A. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Dsus2, also called D suspended second, contains D, E and A. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D Suspended 2nd Piano Chord": "Dsus2 Chord",
      "D Suspended 2nd keyboard and inversions": "Dsus2 piano notes and keyboard diagram",
      "D Suspended 2nd formula": "How is the Dsus2 chord built?",
      "D Suspended 2nd inversions": "Dsus2 inversions",
      "Chord & positions": "Dsus2 piano notes and keyboard diagram",
    },
  },
  "/chords/d-sus4": {
    title: "Dsus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Dsus4 Chord",
    description: "Learn the Dsus4 chord on piano: D, G and A. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Dsus4, also called D suspended fourth, contains D, G and A. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "D Suspended 4th Piano Chord": "Dsus4 Chord",
      "D Suspended 4th keyboard and inversions": "Dsus4 piano notes and keyboard diagram",
      "D Suspended 4th formula": "How is the Dsus4 chord built?",
      "D Suspended 4th inversions": "Dsus4 inversions",
      "Chord & positions": "Dsus4 piano notes and keyboard diagram",
    },
  },
  "/chords/e-7": {
    title: "E7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "E7 Chord",
    description: "Learn the E7 chord on piano: E, G♯, B and D. See the keyboard diagram and three inversions, hear the notes, and download a printable reference.",
    intro: "E7, also called E dominant seventh, contains E, G♯, B and D. Use the piano diagram to find the notes and compare root position with three inversions.",
    theory: "The E7 chord combines a major triad with a minor seventh.",
    fingering: "Finger numbers are not included. The diagrams show note positions, not a prescribed hand shape.",
    h2: {
      "E Dominant Seventh Piano Chord": "E7 Chord",
      "E Dominant Seventh keyboard and inversions": "E7 Piano Notes and Keyboard Diagram",
      "E Dominant Seventh formula": "How the E7 Chord Is Built",
      "E Dominant Seventh positions and inversions": "E7 Chord Inversions",
      "Chord & positions": "E7 Piano Notes and Keyboard Diagram",
      "Compare E Dominant Seventh": "E7 Compared with E Major",
      "Questions about E7": "Questions About E7",
      "Build E7 on the keyboard": "Build E7 on the Keyboard",
      "Print this chord reference": "Print the E7 Chord Reference",
      "Related chord references": "Related Chords and Practice",
    },
  },
  "/chords/e-flat-7": {
    title: "E♭7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "E♭7 Chord",
    description: "Learn the E♭7 chord on piano: E♭, G, B♭ and D♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "E♭7, also called E♭ dominant seventh, contains E♭, G, B♭ and D♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E♭ Dominant Seventh Piano Chord": "E♭7 Chord",
      "E♭ Dominant Seventh keyboard and inversions": "E♭7 piano notes and keyboard diagram",
      "E♭ Dominant Seventh formula": "How is the E♭7 chord built?",
      "E♭ Dominant Seventh positions and inversions": "E♭7 inversions",
      "Chord & positions": "E♭7 piano notes and keyboard diagram",
    },
  },
  "/chords/e-flat-m7": {
    title: "E♭m7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "E♭m7 Chord",
    description: "Learn the E♭m7 chord on piano: E♭, G♭, B♭ and D♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "E♭m7, also called E♭ minor seventh, contains E♭, G♭, B♭ and D♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E♭ Minor Seventh Piano Chord": "E♭m7 Chord",
      "E♭ Minor Seventh keyboard and inversions": "E♭m7 piano notes and keyboard diagram",
      "E♭ Minor Seventh formula": "How is the E♭m7 chord built?",
      "E♭ Minor Seventh positions and inversions": "E♭m7 inversions",
      "Chord & positions": "E♭m7 piano notes and keyboard diagram",
    },
  },
  "/chords/e-flat-m7-flat5": {
    title: "E♭ Half-Diminished Chord (E♭m7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "E♭ Half-Diminished Chord (E♭m7♭5)",
    description: "Learn the E♭ Half-Diminished Chord (E♭m7♭5) on piano: E♭, G♭, B𝄫 and D♭. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "E♭ Half-Diminished Chord (E♭m7♭5) contains E♭, G♭, B𝄫 and D♭. The compact symbol E♭m7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E♭ Half-Diminished Seventh Piano Chord": "E♭ Half-Diminished Chord (E♭m7♭5)",
      "E♭ Half-Diminished Seventh keyboard and inversions": "E♭m7♭5 piano notes and keyboard diagram",
      "E♭ Half-Diminished Seventh formula": "How is the E♭m7♭5 chord built?",
      "E♭ Half-Diminished Seventh positions and inversions": "E♭m7♭5 inversions",
      "Chord & positions": "E♭m7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/e-flat-maj7": {
    title: "E♭maj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "E♭maj7 Chord",
    description: "Learn the E♭maj7 chord on piano: E♭, G, B♭ and D. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "E♭maj7, also called E♭ major seventh, contains E♭, G, B♭ and D. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E♭ Major Seventh Piano Chord": "E♭maj7 Chord",
      "E♭ Major Seventh keyboard and inversions": "E♭maj7 piano notes and keyboard diagram",
      "E♭ Major Seventh formula": "How is the E♭maj7 chord built?",
      "E♭ Major Seventh positions and inversions": "E♭maj7 inversions",
      "Chord & positions": "E♭maj7 piano notes and keyboard diagram",
    },
  },
  "/chords/e-flat-sus2": {
    title: "E♭sus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "E♭sus2 Chord",
    description: "Learn the E♭sus2 chord on piano: E♭, F and B♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "E♭sus2, also called E♭ suspended second, contains E♭, F and B♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E♭ Suspended 2nd Piano Chord": "E♭sus2 Chord",
      "E♭ Suspended 2nd keyboard and inversions": "E♭sus2 piano notes and keyboard diagram",
      "E♭ Suspended 2nd formula": "How is the E♭sus2 chord built?",
      "E♭ Suspended 2nd inversions": "E♭sus2 inversions",
      "Chord & positions": "E♭sus2 piano notes and keyboard diagram",
    },
  },
  "/chords/e-flat-sus4": {
    title: "E♭sus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "E♭sus4 Chord",
    description: "Learn the E♭sus4 chord on piano: E♭, A♭ and B♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "E♭sus4, also called E♭ suspended fourth, contains E♭, A♭ and B♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E♭ Suspended 4th Piano Chord": "E♭sus4 Chord",
      "E♭ Suspended 4th keyboard and inversions": "E♭sus4 piano notes and keyboard diagram",
      "E♭ Suspended 4th formula": "How is the E♭sus4 chord built?",
      "E♭ Suspended 4th inversions": "E♭sus4 inversions",
      "Chord & positions": "E♭sus4 piano notes and keyboard diagram",
    },
  },
  "/chords/e-m7": {
    title: "Em7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Em7 Chord",
    description: "Learn the Em7 chord on piano: E, G, B and D. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Em7, also called E minor seventh, contains E, G, B and D. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Em7 chord is a minor triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E Minor Seventh Piano Chord": "Em7 Chord",
      "E Minor Seventh keyboard and inversions": "Em7 piano notes and keyboard diagram",
      "E Minor Seventh formula": "How is the Em7 chord built?",
      "E Minor Seventh positions and inversions": "Em7 inversions",
      "Chord & positions": "Em7 piano notes and keyboard diagram",
    },
  },
  "/chords/e-m7-flat5": {
    title: "E Half-Diminished Chord (Em7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "E Half-Diminished Chord (Em7♭5)",
    description: "Learn the E Half-Diminished Chord (Em7♭5) on piano: E, G, B♭ and D. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "E Half-Diminished Chord (Em7♭5) contains E, G, B♭ and D. The compact symbol Em7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E Half-Diminished Seventh Piano Chord": "E Half-Diminished Chord (Em7♭5)",
      "E Half-Diminished Seventh keyboard and inversions": "Em7♭5 piano notes and keyboard diagram",
      "E Half-Diminished Seventh formula": "How is the Em7♭5 chord built?",
      "E Half-Diminished Seventh positions and inversions": "Em7♭5 inversions",
      "Chord & positions": "Em7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/e-maj7": {
    title: "Emaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Emaj7 Chord",
    description: "Learn the Emaj7 chord on piano: E, G♯, B and D♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Emaj7, also called E major seventh, contains E, G♯, B and D♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Emaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E Major Seventh Piano Chord": "Emaj7 Chord",
      "E Major Seventh keyboard and inversions": "Emaj7 piano notes and keyboard diagram",
      "E Major Seventh formula": "How is the Emaj7 chord built?",
      "E Major Seventh positions and inversions": "Emaj7 inversions",
      "Chord & positions": "Emaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/e-sus2": {
    title: "Esus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Esus2 Chord",
    description: "Learn the Esus2 chord on piano: E, F♯ and B. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Esus2, also called E suspended second, contains E, F♯ and B. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E Suspended 2nd Piano Chord": "Esus2 Chord",
      "E Suspended 2nd keyboard and inversions": "Esus2 piano notes and keyboard diagram",
      "E Suspended 2nd formula": "How is the Esus2 chord built?",
      "E Suspended 2nd inversions": "Esus2 inversions",
      "Chord & positions": "Esus2 piano notes and keyboard diagram",
    },
  },
  "/chords/e-sus4": {
    title: "Esus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Esus4 Chord",
    description: "Learn the Esus4 chord on piano: E, A and B. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Esus4, also called E suspended fourth, contains E, A and B. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "E Suspended 4th Piano Chord": "Esus4 Chord",
      "E Suspended 4th keyboard and inversions": "Esus4 piano notes and keyboard diagram",
      "E Suspended 4th formula": "How is the Esus4 chord built?",
      "E Suspended 4th inversions": "Esus4 inversions",
      "Chord & positions": "Esus4 piano notes and keyboard diagram",
    },
  },
  "/chords/f-7": {
    title: "F7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "F7 Chord",
    description: "Learn the F7 chord on piano: F, A, C and E♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "F7, also called F dominant seventh, contains F, A, C and E♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The F7 chord is a major triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F Dominant Seventh Piano Chord": "F7 Chord",
      "F Dominant Seventh keyboard and inversions": "F7 piano notes and keyboard diagram",
      "F Dominant Seventh formula": "How is the F7 chord built?",
      "F Dominant Seventh positions and inversions": "F7 inversions",
      "Chord & positions": "F7 piano notes and keyboard diagram",
    },
  },
  "/chords/f-m7": {
    title: "Fm7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Fm7 Chord",
    description: "Learn the Fm7 chord on piano: F, A♭, C and E♭. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Fm7, also called F minor seventh, contains F, A♭, C and E♭. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Fm7 chord is a minor triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F Minor Seventh Piano Chord": "Fm7 Chord",
      "F Minor Seventh keyboard and inversions": "Fm7 piano notes and keyboard diagram",
      "F Minor Seventh formula": "How is the Fm7 chord built?",
      "F Minor Seventh positions and inversions": "Fm7 inversions",
      "Chord & positions": "Fm7 piano notes and keyboard diagram",
    },
  },
  "/chords/f-m7-flat5": {
    title: "F Half-Diminished Chord (Fm7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "F Half-Diminished Chord (Fm7♭5)",
    description: "Learn the F Half-Diminished Chord (Fm7♭5) on piano: F, A♭, C♭ and E♭. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "F Half-Diminished Chord (Fm7♭5) contains F, A♭, C♭ and E♭. The compact symbol Fm7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F Half-Diminished Seventh Piano Chord": "F Half-Diminished Chord (Fm7♭5)",
      "F Half-Diminished Seventh keyboard and inversions": "Fm7♭5 piano notes and keyboard diagram",
      "F Half-Diminished Seventh formula": "How is the Fm7♭5 chord built?",
      "F Half-Diminished Seventh positions and inversions": "Fm7♭5 inversions",
      "Chord & positions": "Fm7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/f-maj7": {
    title: "Fmaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Fmaj7 Chord",
    description: "Learn the Fmaj7 chord on piano: F, A, C and E. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Fmaj7, also called F major seventh, contains F, A, C and E. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Fmaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F Major Seventh Piano Chord": "Fmaj7 Chord",
      "F Major Seventh keyboard and inversions": "Fmaj7 piano notes and keyboard diagram",
      "F Major Seventh formula": "How is the Fmaj7 chord built?",
      "F Major Seventh positions and inversions": "Fmaj7 inversions",
      "Chord & positions": "Fmaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sharp-7": {
    title: "F♯7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "F♯7 Chord",
    description: "Learn the F♯7 chord on piano: F♯, A♯, C♯ and E. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "F♯7, also called F♯ dominant seventh, contains F♯, A♯, C♯ and E. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F♯ Dominant Seventh Piano Chord": "F♯7 Chord",
      "F♯ Dominant Seventh keyboard and inversions": "F♯7 piano notes and keyboard diagram",
      "F♯ Dominant Seventh formula": "How is the F♯7 chord built?",
      "F♯ Dominant Seventh positions and inversions": "F♯7 inversions",
      "Chord & positions": "F♯7 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sharp-m7": {
    title: "F♯m7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "F♯m7 Chord",
    description: "Learn the F♯m7 chord on piano: F♯, A, C♯ and E. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "F♯m7, also called F♯ minor seventh, contains F♯, A, C♯ and E. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F♯ Minor Seventh Piano Chord": "F♯m7 Chord",
      "F♯ Minor Seventh keyboard and inversions": "F♯m7 piano notes and keyboard diagram",
      "F♯ Minor Seventh formula": "How is the F♯m7 chord built?",
      "F♯ Minor Seventh positions and inversions": "F♯m7 inversions",
      "Chord & positions": "F♯m7 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sharp-m7-flat5": {
    title: "F♯ Half-Diminished Chord (F♯m7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "F♯ Half-Diminished Chord (F♯m7♭5)",
    description: "Learn the F♯ Half-Diminished Chord (F♯m7♭5) on piano: F♯, A, C and E. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "F♯ Half-Diminished Chord (F♯m7♭5) contains F♯, A, C and E. The compact symbol F♯m7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F♯ Half-Diminished Seventh Piano Chord": "F♯ Half-Diminished Chord (F♯m7♭5)",
      "F♯ Half-Diminished Seventh keyboard and inversions": "F♯m7♭5 piano notes and keyboard diagram",
      "F♯ Half-Diminished Seventh formula": "How is the F♯m7♭5 chord built?",
      "F♯ Half-Diminished Seventh positions and inversions": "F♯m7♭5 inversions",
      "Chord & positions": "F♯m7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sharp-maj7": {
    title: "F♯maj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "F♯maj7 Chord",
    description: "Learn the F♯maj7 chord on piano: F♯, A♯, C♯ and E♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "F♯maj7, also called F♯ major seventh, contains F♯, A♯, C♯ and E♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F♯ Major Seventh Piano Chord": "F♯maj7 Chord",
      "F♯ Major Seventh keyboard and inversions": "F♯maj7 piano notes and keyboard diagram",
      "F♯ Major Seventh formula": "How is the F♯maj7 chord built?",
      "F♯ Major Seventh positions and inversions": "F♯maj7 inversions",
      "Chord & positions": "F♯maj7 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sharp-sus2": {
    title: "F♯sus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "F♯sus2 Chord",
    description: "Learn the F♯sus2 chord on piano: F♯, G♯ and C♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "F♯sus2, also called F♯ suspended second, contains F♯, G♯ and C♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F♯ Suspended 2nd Piano Chord": "F♯sus2 Chord",
      "F♯ Suspended 2nd keyboard and inversions": "F♯sus2 piano notes and keyboard diagram",
      "F♯ Suspended 2nd formula": "How is the F♯sus2 chord built?",
      "F♯ Suspended 2nd inversions": "F♯sus2 inversions",
      "Chord & positions": "F♯sus2 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sharp-sus4": {
    title: "F♯sus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "F♯sus4 Chord",
    description: "Learn the F♯sus4 chord on piano: F♯, B and C♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "F♯sus4, also called F♯ suspended fourth, contains F♯, B and C♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F♯ Suspended 4th Piano Chord": "F♯sus4 Chord",
      "F♯ Suspended 4th keyboard and inversions": "F♯sus4 piano notes and keyboard diagram",
      "F♯ Suspended 4th formula": "How is the F♯sus4 chord built?",
      "F♯ Suspended 4th inversions": "F♯sus4 inversions",
      "Chord & positions": "F♯sus4 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sus2": {
    title: "Fsus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Fsus2 Chord",
    description: "Learn the Fsus2 chord on piano: F, G and C. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Fsus2, also called F suspended second, contains F, G and C. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F Suspended 2nd Piano Chord": "Fsus2 Chord",
      "F Suspended 2nd keyboard and inversions": "Fsus2 piano notes and keyboard diagram",
      "F Suspended 2nd formula": "How is the Fsus2 chord built?",
      "F Suspended 2nd inversions": "Fsus2 inversions",
      "Chord & positions": "Fsus2 piano notes and keyboard diagram",
    },
  },
  "/chords/f-sus4": {
    title: "Fsus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Fsus4 Chord",
    description: "Learn the Fsus4 chord on piano: F, B♭ and C. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Fsus4, also called F suspended fourth, contains F, B♭ and C. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "F Suspended 4th Piano Chord": "Fsus4 Chord",
      "F Suspended 4th keyboard and inversions": "Fsus4 piano notes and keyboard diagram",
      "F Suspended 4th formula": "How is the Fsus4 chord built?",
      "F Suspended 4th inversions": "Fsus4 inversions",
      "Chord & positions": "Fsus4 piano notes and keyboard diagram",
    },
  },
  "/chords/g-7": {
    title: "G7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "G7 Chord",
    description: "Learn the G7 chord on piano: G, B, D and F. See the keyboard diagram and three inversions, hear the notes, and download a printable reference.",
    intro: "G7, also called G dominant seventh, contains G, B, D and F. Use the piano diagram to find the notes and compare root position with three inversions.",
    theory: "The G7 chord combines a major triad with a minor seventh.",
    fingering: "Finger numbers are not included. The diagrams show note positions, not a prescribed hand shape.",
    h2: {
      "G Dominant Seventh Piano Chord": "G7 Chord",
      "G Dominant Seventh keyboard and inversions": "G7 piano notes and keyboard diagram",
      "G Dominant Seventh formula": "How is the G7 chord built?",
      "G Dominant Seventh positions and inversions": "G7 inversions",
      "Chord & positions": "G7 piano notes and keyboard diagram",
      "Compare G Dominant Seventh": "G7 Compared with G Major",
      "Questions about G7": "Questions About G7",
      "Build G7 on the keyboard": "Build G7 on the Keyboard",
      "Print this chord reference": "Print the G7 Chord Reference",
      "Related chord references": "Related Chords and Practice",
    },
  },
  "/chords/g-m7": {
    title: "Gm7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Gm7 Chord",
    description: "Learn the Gm7 chord on piano: G, B♭, D and F. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Gm7, also called G minor seventh, contains G, B♭, D and F. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Gm7 chord is a minor triad plus a minor seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "G Minor Seventh Piano Chord": "Gm7 Chord",
      "G Minor Seventh keyboard and inversions": "Gm7 piano notes and keyboard diagram",
      "G Minor Seventh formula": "How is the Gm7 chord built?",
      "G Minor Seventh positions and inversions": "Gm7 inversions",
      "Chord & positions": "Gm7 piano notes and keyboard diagram",
    },
  },
  "/chords/g-m7-flat5": {
    title: "G Half-Diminished Chord (Gm7♭5): Piano Notes, Inversions, Sound & PDF",
    h1: "G Half-Diminished Chord (Gm7♭5)",
    description: "Learn the G Half-Diminished Chord (Gm7♭5) on piano: G, B♭, D♭ and F. See keyboard diagrams, explore inversions and hear the chord.",
    intro: "G Half-Diminished Chord (Gm7♭5) contains G, B♭, D♭ and F. The compact symbol Gm7♭5 names the same chord. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "G Half-Diminished Seventh Piano Chord": "G Half-Diminished Chord (Gm7♭5)",
      "G Half-Diminished Seventh keyboard and inversions": "Gm7♭5 piano notes and keyboard diagram",
      "G Half-Diminished Seventh formula": "How is the Gm7♭5 chord built?",
      "G Half-Diminished Seventh positions and inversions": "Gm7♭5 inversions",
      "Chord & positions": "Gm7♭5 piano notes and keyboard diagram",
    },
  },
  "/chords/g-maj7": {
    title: "Gmaj7 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Gmaj7 Chord",
    description: "Learn the Gmaj7 chord on piano: G, B, D and F♯. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Gmaj7, also called G major seventh, contains G, B, D and F♯. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    theory: "The Gmaj7 chord is a major triad plus a major seventh.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "G Major Seventh Piano Chord": "Gmaj7 Chord",
      "G Major Seventh keyboard and inversions": "Gmaj7 piano notes and keyboard diagram",
      "G Major Seventh formula": "How is the Gmaj7 chord built?",
      "G Major Seventh positions and inversions": "Gmaj7 inversions",
      "Chord & positions": "Gmaj7 piano notes and keyboard diagram",
    },
  },
  "/chords/g-sus2": {
    title: "Gsus2 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Gsus2 Chord",
    description: "Learn the Gsus2 chord on piano: G, A and D. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Gsus2, also called G suspended second, contains G, A and D. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "G Suspended 2nd Piano Chord": "Gsus2 Chord",
      "G Suspended 2nd keyboard and inversions": "Gsus2 piano notes and keyboard diagram",
      "G Suspended 2nd formula": "How is the Gsus2 chord built?",
      "G Suspended 2nd inversions": "Gsus2 inversions",
      "Chord & positions": "Gsus2 piano notes and keyboard diagram",
    },
  },
  "/chords/g-sus4": {
    title: "Gsus4 Chord: Piano Notes, Inversions, Sound & PDF",
    h1: "Gsus4 Chord",
    description: "Learn the Gsus4 chord on piano: G, C and D. See keyboard diagrams, explore inversions, hear the chord and practice finding its notes.",
    intro: "Gsus4, also called G suspended fourth, contains G, C and D. Use the piano diagram to find the notes, hear the chord and explore its inversions.",
    fingering: "Fingerings are not included on this page. The diagram shows note positions, not a prescribed hand shape.",
    h2: {
      "G Suspended 4th Piano Chord": "Gsus4 Chord",
      "G Suspended 4th keyboard and inversions": "Gsus4 piano notes and keyboard diagram",
      "G Suspended 4th formula": "How is the Gsus4 chord built?",
      "G Suspended 4th inversions": "Gsus4 inversions",
      "Chord & positions": "Gsus4 piano notes and keyboard diagram",
    },
  },
};
