export type ContinuationLink={label:string;href:string;relation:string};
export type Continuation={sourceObjectId:string;reason:string;primary:ContinuationLink;secondary:ContinuationLink[]};
const practice=(id:string):Continuation=>({sourceObjectId:id,reason:'Check the chord tones in the existing exercise. A chord alone does not identify the key of a song.',primary:{label:'Check these chord tones',href:'#practice',relation:'practice'},secondary:[{label:'Compare possible chord names',href:'/chords/finder',relation:'compare'}]});
export const CONTINUATIONS:Record<string,Continuation>={
 '/chords':{sourceObjectId:'chord-chart',reason:'If you know the notes but not the chord name, compare the Finder’s supported candidates.',primary:{label:'Find a chord from notes',href:'/chords/finder',relation:'identify'},secondary:[{label:'Explore chords in C major',href:'/chords/by-key#c-major',relation:'context'}]},
 '/chords/finder':{sourceObjectId:'chord-finder',reason:'Open a candidate above to inspect its formula and reference voicing. Several names can fit the same notes; none alone determines a song’s key.',primary:{label:'Review the selected notes and candidates',href:'#finder-heading',relation:'compare'},secondary:[{label:'Browse chords by name instead',href:'/chords',relation:'browse'}]},
 '/chords/c-major':{sourceObjectId:'c-major',reason:'Explore C major as the tonic chord in one named key context. The same chord can also occur in other keys.',primary:{label:'See C major in its key context',href:'/chords/by-key?pg-context=c-major#c-major',relation:'context'},secondary:[{label:'Check the chord tones',href:'#practice',relation:'practice'},{label:'Compare the C major scale',href:'/scales/c-major',relation:'scale'}]},
 '/chords/a-minor':practice('a-minor'),'/chords/c-maj7':practice('c-maj7'),'/chords/c-diminished':practice('c-diminished'),'/chords/c-add9':practice('c-add9'),
 '/scales/c-major':{sourceObjectId:'c-major',reason:'Check the scale’s notes, then compare the triads built from the same C major collection.',primary:{label:'Check the scale notes',href:'#check-notes',relation:'practice'},secondary:[{label:'Compare C major’s triads',href:'/chords/by-key?pg-context=c-major#c-major',relation:'context'}]},
 '/keyboard-notes':{sourceObjectId:'keyboard-notes',reason:'Keep this note reference available while practising note locations. The existing round covers a set of notes, not only the selected key.',primary:{label:'Practise note locations',href:'#note-trainer',relation:'practice'},secondary:[{label:'Compare notes in C major',href:'/chords/c-major',relation:'chord'}]},
};
