export const PUBLIC_ROUTES = [
  '/',
  '/tools',
  '/chords',
  '/chords/major',
  '/chords/minor',
  '/chords/diminished',
  '/chords/augmented',
  '/chords/suspended',
  '/chords/seventh',
  '/chords/add',
  '/chords/extended',
  '/chords/altered',
  '/chords/c-add9','/chords/d-flat-add9','/chords/d-add9','/chords/e-flat-add9','/chords/e-add9','/chords/f-add9','/chords/f-sharp-add9','/chords/g-add9','/chords/a-flat-add9','/chords/a-add9','/chords/b-flat-add9','/chords/b-add9',
  '/chords/c-madd9','/chords/d-flat-madd9','/chords/d-madd9','/chords/e-flat-madd9','/chords/e-madd9','/chords/f-madd9','/chords/f-sharp-madd9','/chords/g-madd9','/chords/a-flat-madd9','/chords/a-madd9','/chords/b-flat-madd9','/chords/b-madd9',
  '/chords/a-7','/chords/a-flat-7','/chords/a-flat-m7','/chords/a-flat-m7-flat5','/chords/a-flat-maj7','/chords/a-m7','/chords/a-m7-flat5','/chords/a-maj7',
  '/chords/b-7','/chords/b-flat-7','/chords/b-flat-m7','/chords/b-flat-m7-flat5','/chords/b-flat-maj7','/chords/b-m7','/chords/b-m7-flat5','/chords/b-maj7',
  '/chords/c-7','/chords/c-m7','/chords/c-m7-flat5','/chords/c-maj7',
  '/chords/d-7','/chords/d-flat-7','/chords/d-flat-m7','/chords/d-flat-m7-flat5','/chords/d-flat-maj7','/chords/d-m7','/chords/d-m7-flat5','/chords/d-maj7',
  '/chords/e-7','/chords/e-flat-7','/chords/e-flat-m7','/chords/e-flat-m7-flat5','/chords/e-flat-maj7','/chords/e-m7','/chords/e-m7-flat5','/chords/e-maj7',
  '/chords/f-7','/chords/f-m7','/chords/f-m7-flat5','/chords/f-maj7','/chords/f-sharp-7','/chords/f-sharp-m7','/chords/f-sharp-m7-flat5','/chords/f-sharp-maj7',
  '/chords/g-7','/chords/g-m7','/chords/g-m7-flat5','/chords/g-maj7',
  '/chords/a-augmented',
  '/chords/a-diminished',
  '/chords/a-flat-augmented',
  '/chords/a-flat-diminished',
  '/chords/a-flat-sus2',
  '/chords/a-flat-sus4',
  '/chords/a-sus2',
  '/chords/a-sus4',
  '/chords/b-augmented',
  '/chords/b-diminished',
  '/chords/b-flat-augmented',
  '/chords/b-flat-diminished',
  '/chords/b-flat-sus2',
  '/chords/b-flat-sus4',
  '/chords/b-sus2',
  '/chords/b-sus4',
  '/chords/c-augmented',
  '/chords/c-diminished',
  '/chords/c-sus2',
  '/chords/c-sus4',
  '/chords/d-augmented',
  '/chords/d-diminished',
  '/chords/d-flat-augmented',
  '/chords/d-flat-diminished',
  '/chords/d-flat-sus2',
  '/chords/d-flat-sus4',
  '/chords/d-sus2',
  '/chords/d-sus4',
  '/chords/e-augmented',
  '/chords/e-diminished',
  '/chords/e-flat-augmented',
  '/chords/e-flat-diminished',
  '/chords/e-flat-sus2',
  '/chords/e-flat-sus4',
  '/chords/e-sus2',
  '/chords/e-sus4',
  '/chords/f-augmented',
  '/chords/f-diminished',
  '/chords/f-sharp-augmented',
  '/chords/f-sharp-diminished',
  '/chords/f-sharp-sus2',
  '/chords/f-sharp-sus4',
  '/chords/f-sus2',
  '/chords/f-sus4',
  '/chords/g-augmented',
  '/chords/g-diminished',
  '/chords/g-sus2',
  '/chords/g-sus4',
  '/chords/a-minor',
  '/chords/a-major',
  '/chords/c-major',
  '/chords/g-major',
  '/chords/c-minor',
  '/chords/e-major',
  '/chords/b-major',
  '/chords/a-flat-major',
  '/chords/c-flat-major',
  '/chords/f-major',
  '/chords/d-minor',
  '/chords/e-minor',
  '/chords/d-major',
  '/chords/b-minor',
  '/chords/f-sharp-minor',
  '/chords/c-sharp-minor',
  '/chords/g-sharp-minor',
  '/chords/b-flat-major',
  '/chords/g-minor',
  '/chords/d-flat-major',
  '/chords/e-flat-major',
  '/chords/f-sharp-major',
  '/chords/f-minor',
  '/chords/b-flat-minor',
  '/chords/e-flat-minor',
  '/chords/by-key',
  '/chords/finder',
  '/chord-progressions',
  '/keyboard-notes',
  '/keyboard-notes/labeled',
  '/keyboard-notes/chart',
  '/keyboard-notes/finger-numbers',
  '/scales',
  '/scales/modes',
  '/scales/blues',
  '/scales/pentatonic',
  '/scales/harmonic-major',
  '/scales/chromatic',
  '/scales/c-major',
  '/scales/a-minor',
  '/scales/d-major',
  '/scales/e-minor',
  '/scales/f-major',
  '/scales/g-major',
  '/scales/a-major',
  '/scales/c-minor',
  '/scales/d-minor',
  '/scales/e-major',
  '/scales/b-minor',
  '/scales/f-minor',
  '/scales/a-sharp-minor',
  '/scales/b-major',
  '/scales/b-flat-major',
  '/scales/g-minor',
  '/scales/e-flat-major',
  '/scales/f-sharp-minor',
  '/scales/c-flat-major',
  '/arpeggios',
  '/songs',
  '/songs/easy',
  '/guide',
  '/guide/read-sheet-music',
  '/guide/piano-chords',
  '/guide/piano-scales',
  '/tools/blank-sheet-music',
] as const;

export type PublicRoute = (typeof PUBLIC_ROUTES)[number];

export const CHORD_MAJOR_NAVIGATION = [
  { label: 'C Major', href: '/chords/c-major' },
  { label: 'D♭ Major', href: '/chords/d-flat-major' },
  { label: 'D Major', href: '/chords/d-major' },
  { label: 'E♭ Major', href: '/chords/e-flat-major' },
  { label: 'E Major', href: '/chords/e-major' },
  { label: 'F Major', href: '/chords/f-major' },
  { label: 'F♯ Major', href: '/chords/f-sharp-major' },
  { label: 'G Major', href: '/chords/g-major' },
  { label: 'A♭ Major', href: '/chords/a-flat-major' },
  { label: 'A Major', href: '/chords/a-major' },
  { label: 'B♭ Major', href: '/chords/b-flat-major' },
  { label: 'B Major', href: '/chords/b-major' },
] as const satisfies ReadonlyArray<{ label: string; href: PublicRoute }>;

export const CHORD_MINOR_NAVIGATION = [
  { label: 'C Minor', href: '/chords/c-minor' },
  { label: 'C♯ Minor', href: '/chords/c-sharp-minor' },
  { label: 'D Minor', href: '/chords/d-minor' },
  { label: 'E♭ Minor', href: '/chords/e-flat-minor' },
  { label: 'E Minor', href: '/chords/e-minor' },
  { label: 'F Minor', href: '/chords/f-minor' },
  { label: 'F♯ Minor', href: '/chords/f-sharp-minor' },
  { label: 'G Minor', href: '/chords/g-minor' },
  { label: 'G♯ Minor', href: '/chords/g-sharp-minor' },
  { label: 'A Minor', href: '/chords/a-minor' },
  { label: 'B♭ Minor', href: '/chords/b-flat-minor' },
  { label: 'B Minor', href: '/chords/b-minor' },
] as const satisfies ReadonlyArray<{ label: string; href: PublicRoute }>;

export const CHORD_MORE_NAVIGATION = [
  { label: 'Seventh', href: '/chords/seventh' },
  { label: 'Diminished', href: '/chords/diminished' },
  { label: 'Augmented', href: '/chords/augmented' },
  { label: 'Suspended', href: '/chords/suspended' },
  { label: 'Add', href: '/chords/add' },
  { label: 'Extended', href: '/chords/extended' },
  { label: 'Altered', href: '/chords/altered' },
] as const satisfies ReadonlyArray<{ label: string; href: PublicRoute }>;

export const SCALE_MAJOR_NAVIGATION = [
  { label: 'C Major', href: '/scales/c-major' },
  { label: 'D Major', href: '/scales/d-major' },
  { label: 'E♭ Major', href: '/scales/e-flat-major' },
  { label: 'E Major', href: '/scales/e-major' },
  { label: 'F Major', href: '/scales/f-major' },
  { label: 'G Major', href: '/scales/g-major' },
  { label: 'A Major', href: '/scales/a-major' },
  { label: 'B♭ Major', href: '/scales/b-flat-major' },
  { label: 'B Major', href: '/scales/b-major' },
  { label: 'C♭ Major', href: '/scales/c-flat-major' },
] as const satisfies ReadonlyArray<{ label: string; href: PublicRoute }>;

export const SCALE_MINOR_NAVIGATION = [
  { label: 'C Minor', href: '/scales/c-minor' },
  { label: 'D Minor', href: '/scales/d-minor' },
  { label: 'E Minor', href: '/scales/e-minor' },
  { label: 'F Minor', href: '/scales/f-minor' },
  { label: 'F♯ Minor', href: '/scales/f-sharp-minor' },
  { label: 'G Minor', href: '/scales/g-minor' },
  { label: 'A Minor', href: '/scales/a-minor' },
  { label: 'A♯ Minor', href: '/scales/a-sharp-minor' },
  { label: 'B Minor', href: '/scales/b-minor' },
] as const satisfies ReadonlyArray<{ label: string; href: PublicRoute }>;

export const SCALE_MORE_NAVIGATION = [
  { label: 'Modes', href: '/scales/modes' },
  { label: 'Pentatonic Scales', href: '/scales/pentatonic' },
  { label: 'Blues Scales', href: '/scales/blues' },
  { label: 'Harmonic Major', href: '/scales/harmonic-major' },
  { label: 'Chromatic Scales', href: '/scales/chromatic' },
] as const satisfies ReadonlyArray<{ label: string; href: PublicRoute }>;

export const SITE_NAVIGATION = [
  {
    label: 'Keyboard Notes',
    href: '/keyboard-notes',
    children: [
      { label: 'Labeled Keyboard', href: '/keyboard-notes/labeled' },
      { label: 'Piano Notes Chart', href: '/keyboard-notes/chart' },
      { label: 'Finger Numbers', href: '/keyboard-notes/finger-numbers' },
    ],
  },
  {
    label: 'Chords',
    href: '/chords',
    children: [
      { label: 'Major Chords', href: '/chords/major', group: 'Browse' },
      { label: 'Minor Chords', href: '/chords/minor', group: 'Browse' },
      { label: 'Seventh', href: '/chords/seventh', group: 'More Chords' },
      { label: 'Diminished', href: '/chords/diminished', group: 'More Chords' },
      { label: 'Augmented', href: '/chords/augmented', group: 'More Chords' },
      { label: 'Suspended', href: '/chords/suspended', group: 'More Chords' },
      { label: 'Add', href: '/chords/add', group: 'More Chords' },
      { label: 'Extended', href: '/chords/extended', group: 'More Chords' },
      { label: 'Altered', href: '/chords/altered', group: 'More Chords' },
      { label: 'Chords by Key', href: '/chords/by-key', group: 'Explore' },
      { label: 'Chord Progressions', href: '/chord-progressions', group: 'Explore' },
      { label: 'Chord Finder', href: '/chords/finder', group: 'Explore' },
      { label: 'Piano Chord Guide', href: '/guide/piano-chords', group: 'Learn' },
      { label: 'Finger Numbers', href: '/keyboard-notes/finger-numbers', group: 'Learn' },
    ],
  },
  {
    label: 'Scales',
    href: '/scales',
    children: [
      { label: 'C Major Scale', href: '/scales/c-major' },
      { label: 'A Minor Scale', href: '/scales/a-minor' },
      { label: 'Major & Minor Scales', href: '/scales#chart', group: 'Explore' },
      { label: 'Find by Notes', href: '/scales#find-by-notes', group: 'Explore' },
      { label: 'Modes', href: '/scales/modes' },
      { label: 'Pentatonic Scales', href: '/scales/pentatonic' },
      { label: 'Blues Scales', href: '/scales/blues' },
      { label: 'Chromatic Scales', href: '/scales/chromatic' },
      { label: 'Arpeggios', href: '/arpeggios', group: 'Explore' },
      { label: 'Scale Practice Guide', href: '/guide/piano-scales', group: 'Learn' },
    ],
  },
  {
    label: 'Songs',
    href: '/songs',
    children: [{ label: 'Easy Piano Songs', href: '/songs/easy' }],
  },
  {
    label: 'Guide',
    href: '/guide',
    children: [
      { label: 'Read Sheet Music', href: '/guide/read-sheet-music' },
      { label: 'Piano Chords', href: '/guide/piano-chords' },
      { label: 'Piano Scales', href: '/guide/piano-scales' },
    ],
  },
  {
    label: 'Tools',
    href: '/tools',
    children: [{ label: 'Blank Sheet Music', href: '/tools/blank-sheet-music' }],
  },
] as const satisfies ReadonlyArray<{
  label: string;
  href: PublicRoute;
  children: ReadonlyArray<{ label: string; href: PublicRoute | `${PublicRoute}#${string}`; group?: 'Browse' | 'More Chords' | 'Explore' | 'Learn' }>;
}>;

const publicRouteSet = new Set<string>(PUBLIC_ROUTES);

export function isPublicRoute(url: string): url is PublicRoute {
  return publicRouteSet.has(url);
}
