export const PUBLIC_ROUTES = [
  '/',
  '/tools',
  '/chords',
  '/chords/major',
  '/chords/minor',
  '/chords/diminished',
  '/chords/augmented',
  '/chords/suspended',
  '/chords/seventh',
  '/chords/add',
  '/chords/extended',
  '/chords/altered',
  '/chords/c-add9','/chords/d-flat-add9','/chords/d-add9','/chords/e-flat-add9','/chords/e-add9','/chords/f-add9','/chords/f-sharp-add9','/chords/g-add9','/chords/a-flat-add9','/chords/a-add9','/chords/b-flat-add9','/chords/b-add9',
  '/chords/c-madd9','/chords/d-flat-madd9','/chords/d-madd9','/chords/e-flat-madd9','/chords/e-madd9','/chords/f-madd9','/chords/f-sharp-madd9','/chords/g-madd9','/chords/a-flat-madd9','/chords/a-madd9','/chords/b-flat-madd9','/chords/b-madd9',
  '/chords/a-7','/chords/a-flat-7','/chords/a-flat-m7','/chords/a-flat-m7-flat5','/chords/a-flat-maj7','/chords/a-m7','/chords/a-m7-flat5','/chords/a-maj7',
  '/chords/b-7','/chords/b-flat-7','/chords/b-flat-m7','/chords/b-flat-m7-flat5','/chords/b-flat-maj7','/chords/b-m7','/chords/b-m7-flat5','/chords/b-maj7',
  '/chords/c-7','/chords/c-m7','/chords/c-m7-flat5','/chords/c-maj7',
  '/chords/d-7','/chords/d-flat-7','/chords/d-flat-m7','/chords/d-flat-m7-flat5','/chords/d-flat-maj7','/chords/d-m7','/chords/d-m7-flat5','/chords/d-maj7',
  '/chords/e-7','/chords/e-flat-7','/chords/e-flat-m7','/chords/e-flat-m7-flat5','/chords/e-flat-maj7','/chords/e-m7','/chords/e-m7-flat5','/chords/e-maj7',
  '/chords/f-7','/chords/f-m7','/chords/f-m7-flat5','/chords/f-maj7','/chords/f-sharp-7','/chords/f-sharp-m7','/chords/f-sharp-m7-flat5','/chords/f-sharp-maj7',
  '/chords/g-7','/chords/g-m7','/chords/g-m7-flat5','/chords/g-maj7',
  '/chords/a-augmented',
  '/chords/a-diminished',
  '/chords/a-flat-augmented',
  '/chords/a-flat-diminished',
  '/chords/a-flat-sus2',
  '/chords/a-flat-sus4',
  '/chords/a-sus2',
  '/chords/a-sus4',
  '/chords/b-augmented',
  '/chords/b-diminished',
  '/chords/b-flat-augmented',
  '/chords/b-flat-diminished',
  '/chords/b-flat-sus2',
  '/chords/b-flat-sus4',
  '/chords/b-sus2',
  '/chords/b-sus4',
  '/chords/c-augmented',
  '/chords/c-diminished',
  '/chords/c-sus2',
  '/chords/c-sus4',
  '/chords/d-augmented',
  '/chords/d-diminished',
  '/chords/d-flat-augmented',
  '/chords/d-flat-diminished',
  '/chords/d-flat-sus2',
  '/chords/d-flat-sus4',
  '/chords/d-sus2',
  '/chords/d-sus4',
  '/chords/e-augmented',
  '/chords/e-diminished',
  '/chords/e-flat-augmented',
  '/chords/e-flat-diminished',
  '/chords/e-flat-sus2',
  '/chords/e-flat-sus4',
  '/chords/e-sus2',
  '/chords/e-sus4',
  '/chords/f-augmented',
  '/chords/f-diminished',
  '/chords/f-sharp-augmented',
  '/chords/f-sharp-diminished',
  '/chords/f-sharp-sus2',
  '/chords/f-sharp-sus4',
  '/chords/f-sus2',
  '/chords/f-sus4',
  '/chords/g-augmented',
  '/chords/g-diminished',
  '/chords/g-sus2',
  '/chords/g-sus4',
  '/chords/a-minor',
  '/chords/a-major',
  '/chords/c-major',
  '/chords/g-major',
  '/chords/c-minor',
  '/chords/e-major',
  '/chords/b-major',
  '/chords/a-flat-major',
  '/chords/c-flat-major',
  '/chords/f-major',
  '/chords/d-minor',
  '/chords/e-minor',
  '/chords/d-major',
  '/chords/b-minor',
  '/chords/f-sharp-minor',
  '/chords/c-sharp-minor',
  '/chords/g-sharp-minor',
  '/chords/b-flat-major',
  '/chords/g-minor',
  '/chords/d-flat-major',
  '/chords/e-flat-major',
  '/chords/f-sharp-major',
  '/chords/f-minor',
  '/chords/b-flat-minor',
  '/chords/e-flat-minor',
  '/chords/by-key',
  '/chords/finder',
  '/chord-progressions',
  '/keyboard-notes',
  '/keyboard-notes/labeled',
  '/keyboard-notes/chart',
  '/keyboard-notes/finger-numbers',
  '/scales',
  '/scales/c-major',
  '/scales/a-minor',
  '/songs',
  '/songs/easy',
  '/guide',
  '/guide/read-sheet-music',
  '/guide/piano-chords',
  '/tools/blank-sheet-music',
] as const;

export type PublicRoute = (typeof PUBLIC_ROUTES)[number];

export const SITE_NAVIGATION = [
  {
    label: 'Keyboard Notes',
    href: '/keyboard-notes',
    children: [
      { label: 'Labeled Keyboard', href: '/keyboard-notes/labeled' },
      { label: 'Piano Notes Chart', href: '/keyboard-notes/chart' },
      { label: 'Finger Numbers', href: '/keyboard-notes/finger-numbers' },
    ],
  },
  {
    label: 'Chords',
    href: '/chords',
    children: [
      { label: 'Major Chords', href: '/chords/major', group: 'Browse' },
      { label: 'Minor Chords', href: '/chords/minor', group: 'Browse' },
      { label: 'Diminished Chords', href: '/chords/diminished', group: 'More Chords' },
      { label: 'Augmented Chords', href: '/chords/augmented', group: 'More Chords' },
      { label: 'Suspended Chords', href: '/chords/suspended', group: 'More Chords' },
      { label: 'Seventh Chords', href: '/chords/seventh', group: 'More Chords' },
      { label: 'Add Chords', href: '/chords/add', group: 'More Chords' },
      { label: 'Extended Chords', href: '/chords/extended', group: 'More Chords' },
      { label: 'Altered Chords', href: '/chords/altered', group: 'More Chords' },
      { label: 'Chords by Key', href: '/chords/by-key', group: 'Explore' },
      { label: 'Chord Progressions', href: '/chord-progressions', group: 'Explore' },
      { label: 'Chord Finder', href: '/chords/finder', group: 'Explore' },
      { label: 'Piano Chord Guide', href: '/guide/piano-chords', group: 'Learn' },
      { label: 'Finger Numbers', href: '/keyboard-notes/finger-numbers', group: 'Learn' },
    ],
  },
  {
    label: 'Scales',
    href: '/scales',
    children: [
      { label: 'C Major Scale', href: '/scales/c-major' },
      { label: 'A Minor Scale', href: '/scales/a-minor' },
    ],
  },
  {
    label: 'Songs',
    href: '/songs',
    children: [{ label: 'Easy Piano Songs', href: '/songs/easy' }],
  },
  {
    label: 'Guide',
    href: '/guide',
    children: [
      { label: 'Read Sheet Music', href: '/guide/read-sheet-music' },
      { label: 'Piano Chords', href: '/guide/piano-chords' },
    ],
  },
  {
    label: 'Tools',
    href: '/tools',
    children: [{ label: 'Blank Sheet Music', href: '/tools/blank-sheet-music' }],
  },
] as const satisfies ReadonlyArray<{
  label: string;
  href: PublicRoute;
  children: ReadonlyArray<{ label: string; href: PublicRoute; group?: 'Browse' | 'More Chords' | 'Explore' | 'Learn' }>;
}>;

const publicRouteSet = new Set<string>(PUBLIC_ROUTES);

export function isPublicRoute(url: string): url is PublicRoute {
  return publicRouteSet.has(url);
}
