import { SiteFooter, SiteHeader } from '@/components/chords/site-chrome';
import type { ReactNode } from 'react';
import { PageBreadcrumb } from '@/components/ui/breadcrumb';
import '@/app/chords/a-minor/a-minor.css';
import '@/components/guides/guides.css';
import './scales.css';
import { validateCompletionAuthoringPage } from '@/lib/scale-completion-content';

const Link = ({ href, children }: { href: string; children: ReactNode }) => <a href={href}>{children}</a>;

export function PianoScalesGuidePage() {
  validateCompletionAuthoringPage('/guide/piano-scales');
  return <div className="am-page sc-page"><a className="am-skip" href="#main">Skip to content</a><SiteHeader search={null} current="Guide"/><main id="main" className="pr-container" tabIndex={-1}>
    <header className="am-page-heading"><PageBreadcrumb items={[{ label: 'Guide', href: '/guide' }, { label: 'Piano scales' }]}/><h1>Piano scales for beginners</h1><p className="am-direct-answer">Start with one scale, one hand and one octave. Check the notes before adding a steady beat, then finish with one specific detail to revisit.</p></header>
    <nav className="sc-jumps" aria-label="On this page"><a href="#choose-a-scale">Choose a scale</a><a href="#minor-forms">Minor forms</a><a href="#fingering">Fingering</a><a href="#routine">Practice routine</a><a href="#practice-tools">Practice tools</a><a href="#printable">Printable reference</a><a href="#faq">Questions</a></nav>
    <article className="am-reading gd-reading sc-guide">
      <section className="am-content-section"><h2>Start with one task</h2><div className="am-content-body"><p>A useful practice session ends with something specific to remember: a note you corrected, a fingering you checked or a setting to use next time.</p><p>You do not need to work through every scale in one sitting. Use this guide alongside the <Link href="/scales">piano scale chart</Link>, rather than treating a long list of keys as a daily assignment.</p></div></section>
      <section className="am-content-section" id="choose-a-scale"><h2>Choose one clear starting point</h2><div className="am-content-body"><p>For a first reference, open <Link href="/scales/c-major">C major</Link>. Its ascending notes are <strong>C-D-E-F-G-A-B-C</strong>. In the right-hand reference, C4 to C5 is one octave. The last C is a higher occurrence of the starting note, not a new eighth scale degree. The major-scale step pattern is whole-whole-half-whole-whole-whole-half.</p><p>Use the note names, keyboard and staff together. The keyboard shows where a sound is played; the staff and labels preserve its written name and register. When you change direction, read the new sequence instead of assuming the display is unchanged.</p><p>Already practicing another scale? Open that scale directly. Read its form, hand, direction and range before using the finger numbers.</p></div></section>
      <section className="am-content-section" id="minor-forms"><h2>Check the form before practicing minor</h2><div className="am-content-body"><p><Link href="/scales/a-minor">A minor</Link> contains three references here. A natural minor uses A-B-C-D-E-F-G. Harmonic minor raises G to G♯. In the classical melodic-minor scale exercise, the ascent raises F and G; the descent returns to the natural-minor collection. C major shares its note collection with <strong>A natural minor</strong>, not with all three forms.</p><p>The classical exercise convention is not a rule that every melody must lower those notes whenever it descends. Read the music in front of you and the convention named by your reference.</p></div></section>
      <section className="am-content-section" id="fingering"><h2>Use a fingering with the right scope</h2><div className="am-content-body"><p>Select the hand you are practicing. Then check that the numbers apply to the same direction and one-octave range shown on the page. A right-hand row is not a left-hand instruction.</p><p>For the C-major right-hand ascending reference, the numbers are <strong>1-2-3-1-2-3-4-5</strong>. The left-hand ascending reference uses <strong>5-4-3-2-1-3-2-1</strong>. These are source-documented one-octave rows, not a universal pattern for every scale or range.</p><p>Look ahead to the place where the finger pattern changes. Work on a small part of that row before playing the whole octave again. A teacher can help you choose and use a fingering for your own playing situation.</p><p>A “Notes only” message means PianoGrid has not provided a source-checked fingering for that exact selection. You can still read or hear the notes; do not borrow numbers from another form or hand.</p></div></section>
      <section className="am-content-section" id="routine"><h2>Try this short routine</h2><div className="am-content-body"><p>This is an optional ten-minute outline, not a required pace or a promise of progress. Shorten a step when you have answered its question; spend more time on a specific uncertainty rather than restarting everything.</p><div className="am-table-scroll" role="region" tabIndex={0} aria-label="Optional practice routine"><table className="sc-data-table"><thead><tr><th>Part</th><th>What to do</th><th>What to notice</th></tr></thead><tbody>
        <tr><td>About 2 minutes: read</td><td>Say the scale name, form and note sequence. Compare one note on the staff with its key.</td><td>Can you explain which reference you selected?</td></tr>
        <tr><td>About 3 minutes: prepare</td><td>Use one hand without guided playback. Check a small section around a finger change, then the full octave.</td><td>Which note or change needs another look?</td></tr>
        <tr><td>About 3 minutes: follow</td><td>Choose a comfortable supported tempo, one note per beat and one pass. Stop to correct a specific problem.</td><td>Are you following the intended sequence, rather than racing the sound?</td></tr>
        <tr><td>About 2 minutes: check</td><td>Answer a note question or cover a note row and recall it. Write down one thing to revisit.</td><td>What will you work on next time?</td></tr>
      </tbody></table></div><p>Do not force a tempo because the control allows it. Guided playback is a reference, not an instruction to keep going when you need to stop. Changing a setting stops the session so you can restart with a clear new reference.</p></div></section>
      <section className="am-content-section" id="practice-tools"><h2>Understand what the practice tools measure</h2><div className="am-content-body"><p>The note checks ask about the displayed musical information. A set question can identify a missing or extra note. An order question checks the sequence, including its direction and octave endpoint. A classical-minor question checks the named ascending or descending convention.</p><p>These questions do <strong>not</strong> listen to your piano. Guided playback provides notes and a beat; it does not measure your timing or technique. “I practiced this” is your own record of a session, not a performance score.</p><p>Use <strong>Show answer</strong> when needed. It is a reference action, not an independently correct attempt. After reading the explanation, try again with the answer covered.</p></div></section>
      <section className="am-content-section" id="compare"><h2>Make one comparison</h2><div className="am-content-body"><p>Choose a question, rather than switching randomly between many scales. Compare C major with A natural minor to notice a shared collection and different tonic. Compare C major with C natural minor to notice what changes while the tonic stays C.</p><p>For a small original exploration, play C-E-G-E-C after the C-major scale. Compare that chord-tone pattern with the stepwise scale. Then look at the C-major example in <Link href="/arpeggios#c-major">arpeggios</Link>. This is a limited exercise, not a rule that every note in the scale will suit every chord or song.</p></div></section>
      <section className="am-content-section" id="printable"><h2>Keep a useful reference</h2><div className="am-content-body"><p>Print the current scale when you need one selection beside the piano. Use the resource title and coverage list to choose a larger note reference. A fixed PDF does not automatically inherit the form or direction currently selected on the webpage.</p><p>The C-major two-hand starter shows both hands in an explicitly labeled one-octave reference. It is separate from the single-hand guided-playback mode. A resource with both staves is not evidence that the website checks two-hand coordination.</p><p>Write down the scale, form, hand, direction, tempo and one observation. On your next visit, choose the same settings deliberately and decide what to revisit.</p></div></section>
      <section className="am-content-section" id="faq"><h2>Common questions</h2><div className="am-content-body sc-faq-list"><details><summary>Should I practice all scales every day?</summary><p>This guide does not prescribe that. Start with a specific task you can check. An existing lesson or practice plan may require a different selection.</p></details><details><summary>Is faster always better?</summary><p>Speed is only one setting in this tool. The routine uses a clear sequence and a specific observation; it does not award a technique score for a higher BPM.</p></details><details><summary>Can I use one-octave finger numbers for two octaves?</summary><p>Do not extend this reference by repeating its array of numbers. Use a source that explicitly covers the longer range and its transitions.</p></details><details><summary>Did PianoGrid hear me play correctly?</summary><p>No. The webpage grades submitted note-knowledge answers. Guided playback and your completion mark are separate from performance detection.</p></details></div></section>
      <section className="am-content-section"><h2>Your next step</h2><div className="am-content-body"><p>Open <Link href="/scales/c-major#practice">C major practice</Link>, check the displayed settings and try one pass. Choose a different supported scale through the <Link href="/scales">scale chart</Link> when your own practice task calls for it.</p></div></section>
      <section className="am-content-section" id="sources"><h2>Sources and scope</h2><div className="am-content-body"><p>Scale notes, intervals and C-major fingerings use the source records linked from their reference pages. The minor-form explanation is supported by <a href="https://viva.pressbooks.pub/openmusictheory/chapter/minor-scales/">Open Music Theory: Minor Scales</a> and <a href="https://www.open.edu/openlearn/history-the-arts/music/an-introduction-music-theory/content-section-5.9">OpenLearn: Minor scales</a>. The routine, comparisons and time allocations are PianoGrid editorial suggestions, not a teacher-reviewed prescription or effectiveness claim.</p></div></section>
    </article>
  </main><SiteFooter url="/guide/piano-scales"/></div>;
}
