const results=[];
const pass=name=>results.push({name,passed:true});
globalThis.pilotResults=results;
await page.goto('http://localhost:3127/chords/c-major',{waitUntil:'domcontentloaded'});
await expect(page.getByRole('button',{name:'Play chord',exact:true})).toBeEnabled();
await expect(page.locator('.cp-panels [data-state=open]')).toHaveCount(0);pass('Panels initially closed');
await page.getByRole('button',{name:'Play chord',exact:true}).click();
await expect(page.locator('.cp-workspace')).toHaveAttribute('data-audio-state','playing');
await page.getByRole('button',{name:'Stop',exact:true}).click();
await expect(page.locator('.cp-workspace .am-is-sounding')).toHaveCount(0);pass('Play and Stop');
await page.getByRole('radio',{name:'First inversion',exact:true}).check();
await expect(page.locator('#note-order')).toHaveText('E4 – G4 – C5');pass('First inversion synchronized');
await page.getByRole('button',{name:'Fingering',exact:true}).click();
await expect(page.getByText('No verified fingering is shown for this inversion.',{exact:true})).toBeVisible();
await page.getByRole('radio',{name:'Left hand',exact:true}).check();
await page.getByRole('radio',{name:'Root position',exact:true}).check();
await expect(page.getByText('Left-hand root position',{exact:true})).toBeVisible();pass('Hand and inversion scope');
await page.getByRole('button',{name:'Staff notation',exact:true}).click();
await expect(page.locator('.cp-panels [data-state=open]')).toHaveCount(1);
await expect(page.locator('#c-major-staff [data-midi]')).toHaveCount(3);pass('Staff and one-open-panel');
const c=page.getByRole('button',{name:'C4, reference note',exact:true});await c.focus();await page.keyboard.down('Space');
await expect(c).toHaveClass(/cp-pressed/);await page.keyboard.up('Space');await expect(c).not.toHaveClass(/cp-pressed/);pass('Keyboard hold/release');
await page.getByRole('button',{name:'Start practice',exact:true}).click();
await expect(page.locator('.cp-workspace')).toHaveAttribute('data-mode','practice');
await expect(page.locator('main .am-key[data-target]')).toHaveCount(0);
await expect(page.locator('.am-direct-answer')).toBeHidden();await expect(page.locator('.cp-panels')).toBeHidden();
await expect(page.getByRole('button',{name:'Check answer',exact:true})).toBeDisabled();pass('Practice hides reference answers');
for(const name of ['C4','E4','F♯4'])await page.getByRole('button',{name,exact:true}).click();
await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('#practice')).toHaveAttribute('data-practice-state','wrong');
await page.getByRole('button',{name:'F♯4',exact:true}).click();await page.getByRole('button',{name:'G4',exact:true}).click();
await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('.cp-result')).toHaveText('Correct after retrying, without a hint.');pass('Wrong then correct classified as retry');
await page.getByRole('button',{name:'Hint',exact:true}).click();await page.getByRole('button',{name:'Show answer',exact:true}).click();
await page.getByRole('button',{name:'Try again',exact:true}).click();
for(const name of ['C4','E4','G4'])await page.getByRole('button',{name,exact:true}).click();
await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('#practice')).toHaveAttribute('data-answer-kind','revealed');pass('Reveal survives retry');
await page.getByRole('button',{name:'View reference',exact:true}).click();
await page.getByRole('button',{name:'Resume practice',exact:true}).click();
await expect(page.locator('.cp-selected')).toContainText('C · E · G');await expect(page.locator('#practice')).toHaveAttribute('data-answer-kind','revealed');pass('Resume preserves selection and help');
const fs=await import('node:fs/promises'),file=artifactPath('browser-interactions.json');await fs.writeFile(file,JSON.stringify(results,null,2));return {results,file};
