'use client';
import { usePilotPractice } from '@/lib/product-measurement';
import {useContext,useEffect,useMemo,useState} from 'react';
import type {AddChordPractice,ChordDetailData,ChordPractice} from '@/lib/a-minor-types';
import {SelectedVoicingContext,StopPlaybackContext} from '../a-minor/experience';

const KEYS=[
 {pc:0,label:'C',black:false},{pc:1,label:'C♯ / D♭',black:true},{pc:2,label:'D',black:false},{pc:3,label:'D♯ / E♭',black:true},
 {pc:4,label:'E',black:false},{pc:5,label:'F',black:false},{pc:6,label:'F♯ / G♭',black:true},{pc:7,label:'G',black:false},
 {pc:8,label:'G♯ / A♭',black:true},{pc:9,label:'A',black:false},{pc:10,label:'A♯ / B♭',black:true},{pc:11,label:'B',black:false},
];
const keyClass:Record<number,string>={0:'c',1:'cs',2:'d',3:'ds',4:'e',5:'f',6:'fs',7:'g',8:'gs',9:'a',10:'as',11:'b'};
const pc=(midi:number)=>((midi%12)+12)%12;
const sorted=(values:number[])=>[...values].sort((a,b)=>a-b);
const same=(a:number[],b:number[])=>JSON.stringify(sorted(a))===JSON.stringify(sorted(b));
const isAddPractice=(practice:ChordPractice):practice is AddChordPractice=>'kind' in practice&&practice.kind==='add';
const octave=(midi:number)=>Math.floor(midi/12)-1;
const genericNames=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];

function BasicPractice({data,practice}:{data:ChordDetailData;practice:ChordPractice}){
 const [ready,setReady]=useState(false),[selected,setSelected]=useState<number[]>([]),[feedback,setFeedback]=useState<{kind:'success'|'error'|'info';text:string}|null>(null);
 const measurement=usePilotPractice(data.namespace,'chord-builder');
 useEffect(()=>{if(feedback?.kind==='success')measurement.complete();},[feedback]);
 useEffect(()=>setReady(true),[]);
 const root=data.voicings.find(voicing=>voicing.voicing_id===data.defaultId)!;
 const answer=useMemo(()=>root.notes_low_to_high.map(note=>pc(note.midi)),[root]);
 const answerNames=new Map(answer.map((value,index)=>[value,data.chord.note_spellings[index]]));
 const display=(value:number)=>answerNames.get(value)||KEYS.find(key=>key.pc===value)!.label;
 const countWord=practice.requiredPitchClassCount===3?'three':practice.requiredPitchClassCount===4?'four':String(practice.requiredPitchClassCount);
 function toggle(value:number){measurement.start();setSelected(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);setFeedback(null);}
 function check(){measurement.start();if(selected.length===0){setFeedback({kind:'error',text:`No notes selected. Choose the ${countWord} pitch classes in ${data.chord.symbol}, then check again.`});return;}const missing=answer.filter(value=>!selected.includes(value)),extra=selected.filter(value=>!answer.includes(value));if(!missing.length&&!extra.length){setFeedback({kind:'success',text:`Correct: ${data.chord.symbol} contains ${data.chord.note_spellings.join(', ')}. Octave and selection order do not affect this check.`});return;}const parts=[];if(missing.length)parts.push(`Missing: ${missing.map(display).join(', ')}`);if(extra.length)parts.push(`Extra: ${extra.map(display).join(', ')}`);setFeedback({kind:'error',text:`Not yet. ${parts.join('. ')}.`});}
 return <section className="am-content-section ch-practice" id="practice" data-block-id="practice" data-practice-state={feedback?.kind||'unanswered'} tabIndex={-1} aria-labelledby="practice-heading"><div className="ch-section-heading"><div className="ch-section-kicker">Interactive practice</div><h2 id="practice-heading">{practice.heading}</h2></div><div className="am-content-body ch-learning-panel"><p>{practice.prompt}</p><p>{practice.scope}</p><div className="ch-practice-task"><div><span className="ch-practice-count">{practice.requiredPitchClassCount}</span><strong>Choose {countWord} pitch classes</strong></div><p>One octave, C through B. Select a key again to remove it.</p></div><fieldset className="ch-practice-fieldset" disabled={!ready}><legend className="pr-sr-only">One-octave keyboard from C through B</legend><div className="ch-practice-keyboard">{KEYS.map(key=><button key={key.pc} type="button" className={`ch-practice-key ${key.black?'is-black':'is-white'} key-${keyClass[key.pc]}`} aria-label={`${key.label} pitch class`} aria-pressed={selected.includes(key.pc)} onClick={()=>toggle(key.pc)}><span>{key.label}</span></button>)}</div></fieldset><div className="ch-current-selection"><strong>Selected:</strong> <span>{selected.length?selected.map(display).join(' · '):'none'}</span></div><div className="ch-practice-actions"><button className="am-button am-primary" type="button" disabled={!ready} onClick={check}>Check answer</button><button className="am-button am-secondary" type="button" disabled={!ready} onClick={()=>{measurement.reset();setSelected([]);setFeedback(null);}}>Try again</button><button className="am-button am-tertiary" type="button" disabled={!ready} onClick={()=>{measurement.reveal();setSelected([...answer]);setFeedback({kind:'info',text:`Answer shown: ${data.chord.note_spellings.join(', ')}. This reveal is not recorded as a correct attempt.`});}}>Show answer</button></div><div className={`ch-practice-feedback${feedback?` is-${feedback.kind}`:''}`} role="status" aria-live="polite" aria-atomic="true">{feedback?.text||'Choose notes, then check your answer.'}</div><noscript><details className="ch-static-answer"><summary>Show the non-interactive answer</summary><p>{data.chord.symbol} uses the pitch classes {data.chord.note_spellings.join(', ')}. JavaScript is required to select keys and receive feedback.</p></details></noscript></div></section>;
}

function AddPractice({data,practice}:{data:ChordDetailData;practice:AddChordPractice}){
 const activeId=useContext(SelectedVoicingContext)||data.defaultId,stopPlayback=useContext(StopPlaybackContext),active=data.voicings.find(item=>item.voicing_id===activeId)!;
 const [ready,setReady]=useState(false),[mode,setMode]=useState<'chordTones'|'matchExample'>(practice.defaultMode),[selected,setSelected]=useState<number[]>([]),[feedback,setFeedback]=useState<{kind:'success'|'error'|'info';text:string}|null>(null);
 const measurement=usePilotPractice(data.namespace,mode);
 useEffect(()=>{if(feedback?.kind==='success')measurement.complete();},[feedback]);
 useEffect(()=>setReady(true),[]);useEffect(()=>{setSelected([]);setFeedback(null);},[activeId,mode]);
 const definitionPcs=practice.modes[0].expectedPitchClasses,target=active.notes_low_to_high.map(note=>note.midi),targetPcSet=[...new Set(target.map(pc))];
 const preferred=new Map<number,string>();data.chord.note_spellings.forEach((name,index)=>preferred.set(pc(data.voicings[0].notes_low_to_high[index].midi),name));
 const label=(midi:number)=>`${preferred.get(pc(midi))||genericNames[pc(midi)]}${octave(midi)}`;
 function toggle(midi:number){measurement.start();setSelected(current=>current.includes(midi)?current.filter(item=>item!==midi):[...current,midi]);setFeedback(null);}
 function changeMode(next:'chordTones'|'matchExample'){measurement.reset();stopPlayback();setMode(next);}
 function clear(){measurement.reset();stopPlayback();setSelected([]);setFeedback(null);}
 function check(){measurement.start();if(!selected.length){setFeedback({kind:'error',text:'No notes selected. Choose four chord tones, then check again.'});return;}const selectedPcSet=[...new Set(selected.map(pc))];if(mode==='chordTones'){const missing=targetPcSet.filter(value=>!selectedPcSet.includes(value)),extra=selectedPcSet.filter(value=>!targetPcSet.includes(value));if(!missing.length&&!extra.length){setFeedback({kind:'success',text:`Correct: ${data.chord.symbol} contains ${data.chord.note_spellings.join(', ')}. Octave doublings and selection order do not change this pitch-class check.`});return;}const parts=[];if(missing.length)parts.push(`Missing: ${missing.map(value=>preferred.get(value)||genericNames[value]).join(', ')}`);if(extra.length)parts.push(`Extra: ${extra.map(value=>genericNames[value]).join(', ')}`);setFeedback({kind:'error',text:`Not yet. ${parts.join('. ')}.`});return;}if(same(selected,target)){setFeedback({kind:'success',text:`Correct: you matched ${active.notes_low_to_high.map(note=>note.display_pitch).join(', ')}.`});return;}if(same(selectedPcSet,targetPcSet)){setFeedback({kind:'info',text:practice.modes[1].samePitchClassesWrongRegisterFeedback});return;}const missing=targetPcSet.filter(value=>!selectedPcSet.includes(value)),extra=selectedPcSet.filter(value=>!targetPcSet.includes(value));const parts=[];if(missing.length)parts.push(`Missing chord tone: ${missing.map(value=>preferred.get(value)||genericNames[value]).join(', ')}`);if(extra.length)parts.push(`Extra chord tone: ${extra.map(value=>genericNames[value]).join(', ')}`);setFeedback({kind:'error',text:`Not yet. ${parts.join('. ')||'Match the four displayed pitches.'}.`});}
 function show(){measurement.reveal();stopPlayback();const answer=mode==='matchExample'?target:data.voicings[0].notes_low_to_high.map(note=>note.midi);setSelected([...answer]);setFeedback({kind:'info',text:`Answer shown: ${(mode==='matchExample'?active.notes_low_to_high.map(note=>note.display_pitch):data.chord.note_spellings).join(', ')}. This reveal is not recorded as a correct attempt.`});}
 const [minimum,maximum]=practice.midiRange,buttons=Array.from({length:maximum-minimum+1},(_,index)=>minimum+index);
 return <section className="am-content-section ch-practice ch-add-practice" id="practice" data-block-id="practice" data-practice-mode={mode} data-active-example={activeId} data-practice-state={feedback?.kind||'unanswered'} tabIndex={-1} aria-labelledby="practice-heading"><div className="ch-section-heading"><div className="ch-section-kicker">Interactive practice</div><h2 id="practice-heading">{practice.heading}</h2></div><div className="am-content-body ch-learning-panel"><p>{practice.prompt}</p><p>{practice.scope}</p><fieldset className="ch-mode-fieldset" disabled={!ready}><legend>Choose a task</legend><div className="ch-mode-options">{practice.modes.map(item=><label key={item.id}><input type="radio" name="practice-mode" value={item.id} checked={mode===item.id} onChange={()=>changeMode(item.id)}/><span>{item.label}</span></label>)}</div></fieldset><div className="ch-practice-task"><div><span className="ch-practice-count">4</span><strong>{practice.modes.find(item=>item.id===mode)!.label}</strong></div><p>{practice.modes.find(item=>item.id===mode)!.instruction}</p></div><fieldset className="ch-midi-fieldset" disabled={!ready}><legend>Select pitches from C3 through E5</legend><div className="ch-midi-grid">{buttons.map(midi=><button key={midi} type="button" className={`ch-midi-key ${[1,3,6,8,10].includes(pc(midi))?'is-black':'is-white'}`} aria-pressed={selected.includes(midi)} onClick={()=>toggle(midi)}>{label(midi)}</button>)}</div></fieldset><div className="ch-current-selection"><strong>Selected:</strong> <span>{selected.length?sorted(selected).map(label).join(' · '):'none'}</span></div><div className="ch-practice-actions"><button className="am-button am-primary" type="button" disabled={!ready} onClick={check}>Check answer</button><button className="am-button am-secondary" type="button" disabled={!ready} onClick={clear}>Clear</button><button className="am-button am-tertiary" type="button" disabled={!ready} onClick={show}>Show answer</button></div><div className={`ch-practice-feedback${feedback?` is-${feedback.kind}`:''}`} role="status" aria-live="polite" aria-atomic="true">{feedback?.text||'Choose notes, then check your answer.'}</div><noscript><details className="ch-static-answer"><summary>Show the non-interactive answer</summary><p>{data.chord.symbol} uses the pitch classes {data.chord.note_spellings.join(', ')}. Both authored layouts remain listed above.</p></details></noscript></div></section>;
}

export function ChordBuilderPractice(props:{data:ChordDetailData;practice:ChordPractice}){return isAddPractice(props.practice)?<AddPractice data={props.data} practice={props.practice}/>:<BasicPractice {...props}/>;}
