'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { CompletionReference, CompletionRealization } from '@/lib/chord-completion-content';
import { ReferenceAudio, type AudioStatus } from '@/lib/a-minor-audio';
import type { Voicing } from '@/lib/a-minor-types';
import { PlaybackControls } from './playback-controls';
import { KeyboardViewport } from './keyboard-viewport';
import {emitChordEvent} from '@/lib/chord-events';

const label = (value: string) => value.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, char => char.toUpperCase());
const pc = (midi: number) => ((midi % 12) + 12) % 12;
const unique = (values: number[]) => [...new Set(values)].sort((a, b) => a - b);
const same = (a: number[], b: number[]) => a.length === b.length && a.every((value, index) => value === b[index]);
function asVoicing(item: CompletionReference, realization: CompletionRealization): Voicing {
  const events = (source: CompletionRealization['audio']['block']) => source.map(event => ({ midi: event.midi, frequency_hz: 440 * 2 ** ((event.midi - 69) / 12), onset_ms: event.onsetMs, duration_ms: event.durationMs }));
  return { voicing_id: `${item.id}--${realization.id}`, inversion_label: realization.label, chord_symbol: realization.symbol, bass_spelling: realization.notes[0], notes_low_to_high: realization.notes.map((display_pitch, index) => ({ display_pitch, midi: realization.midi[index] })), diagram: { keyboard_range_midi: [realization.keyboard.minMidi, realization.keyboard.maxMidi], highlight_midi: [...realization.midi], alt_text: `${item.name}, ${realization.label}: ${realization.notes.join(', ')}.` }, playback: { together: events(realization.audio.block), ascending: events(realization.audio.ascending) }, print_data: { spelled_pitches: [...realization.notes], highlight_midi: [...realization.midi] } };
}
export function CompletionCategoryExperience({ items, defaultObjectId, family, pdf, allRoots }: { items: CompletionReference[]; defaultObjectId: string; family: 'extended' | 'altered'; pdf: string; allRoots:{heading:string;paragraphs:string[]} }) {
  const [root, setRoot] = useState(''), [subtype, setSubtype] = useState(''), [query, setQuery] = useState(''), [selectedId, setSelectedId] = useState(defaultObjectId), [realizationId, setRealizationId] = useState('rooted-example'), [ready, setReady] = useState(false);
  const [audio, setAudio] = useState<{ state: AudioStatus; message: string; mode: 'together' | 'ascending' | null }>({ state: 'idle', message: '', mode: null }), [sounding, setSounding] = useState<number[]>([]);
  const [practiceMode, setPracticeMode] = useState<'formula_pitch_classes' | 'example_pitch_classes' | 'example_midi_set'>('formula_pitch_classes'), [answer, setAnswer] = useState<number[]>([]), [feedback, setFeedback] = useState('');
  const player = useRef<ReferenceAudio | null>(null);
  useEffect(() => { const p = new ReferenceAudio((state, message, mode) => setAudio({ state, message, mode }), setSounding, { loading: 'Preparing sound…', audio_error: 'Sound could not start. Try again.', audio_unavailable: 'Sound is unavailable in this browser.' }); player.current = p; setReady(true); return () => p.dispose(); }, []);
  const filtered = useMemo(() => items.filter(item => (!root || item.root === root) && (!subtype || item.subtype === subtype) && (!query.trim() || [item.name, item.symbol, ...item.aliases].join(' ').toLowerCase().includes(query.trim().toLowerCase()))), [items, query, root, subtype]);
  const selected = items.find(item => item.id === selectedId) || items[0];
  const realization = selected.realizations.find(item => item.id === realizationId) || selected.realizations.find(item => item.id === selected.defaultRealizationId) || selected.realizations[0];
  const voicing = asVoicing(selected, realization);
  const formulaPcs = unique(selected.definition.pitchClassIntervals.map(interval => (selected.rootPitchClass + interval) % 12));
  const examplePcs = unique(realization.midi.map(pc));
  const expected = practiceMode === 'formula_pitch_classes' ? formulaPcs : practiceMode === 'example_pitch_classes' ? examplePcs : [...realization.midi].sort((a, b) => a - b);
  const answerOptions = practiceMode === 'example_midi_set' ? Array.from({ length: realization.keyboard.maxMidi - realization.keyboard.minMidi + 1 }, (_, i) => realization.keyboard.minMidi + i) : Array.from({ length: 12 }, (_, i) => i);
  function chooseObject(id: string) { player.current?.cancel('Playback stopped.', 'stopped'); setSelectedId(id); const next = items.find(item => item.id === id)!; setRealizationId(next.defaultRealizationId); setAnswer([]); setFeedback(''); emitChordEvent('chord_result_selected',{objectId:next.id,family:next.family,origin:`${family}_category`}); }
  function check() { const current = unique(answer); const target = unique(expected),correct=same(current,target); if (correct) setFeedback('Correct for this named task.'); else if (practiceMode === 'example_midi_set' && same(unique(answer.map(pc)), examplePcs)) setFeedback('The chord tones are correct. Now match the octaves shown in this example.'); else { const missing = target.filter(value => !current.includes(value)); const extra = current.filter(value => !target.includes(value)); setFeedback(`${missing.length ? `Missing: ${missing.join(', ')}. ` : ''}${extra.length ? `Extra: ${extra.join(', ')}.` : ''}`.trim()); } emitChordEvent('practice_answer',{taskMode:practiceMode,outcome:correct?'correct':'incorrect',answerShown:false}); }
  return <section id="all-roots" className="cc-explorer" aria-labelledby="cc-heading"><div className="cc-heading"><div><p className="sp-overline">{items.length} server-rendered references</p><h2 id="cc-heading">{allRoots.heading}</h2>{allRoots.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div><p>Filters change this view only. Every reference remains in the initial page HTML.</p></div>
    <div className="cc-filters"><label>Search name or symbol<input type="search" value={query} onChange={event => setQuery(event.target.value)}/></label><label>Root<select value={root} onChange={event => setRoot(event.target.value)}><option value="">All roots</option>{[...new Set(items.map(item => item.root))].map(value => <option key={value}>{value}</option>)}</select></label><label>Type<select value={subtype} onChange={event => setSubtype(event.target.value)}><option value="">All types</option>{[...new Set(items.map(item => item.subtype))].map(value => <option key={value}>{label(value)}</option>)}</select></label><button className="am-button am-secondary" type="button" disabled={!query && !root && !subtype} onClick={() => { setQuery(''); setRoot(''); setSubtype(''); }}>Clear filters</button></div>
    <div className="cc-workspace"><article className="cc-preview" aria-live="polite"><header><div><p className="sp-overline">Current reference · {family}</p><h3>{selected.symbol} <span>{selected.name}</span></h3></div><div className="cc-preview-actions"><a className="am-button am-tertiary" href={pdf} download onClick={()=>emitChordEvent('reference_download_clicked',{assetId:pdf})}>Download starter PDF</a><button className="am-button am-secondary" type="button" onClick={()=>{emitChordEvent('print_opened',{objectId:selected.id,realizationId:realization.id});window.print();}}>Print current view</button></div></header><dl className="cc-facts"><div><dt>Formula inventory</dt><dd>{selected.definition.displayFormula.join(' – ')}</dd></div><div><dt>Written tones</dt><dd>{selected.definition.toneSpellings.join(' · ')}</dd></div><div><dt>Root</dt><dd>{selected.root}</dd></div><div><dt>Type</dt><dd>{label(selected.subtype)}</dd></div></dl><label className="cc-layout">View<select value={realization.id} onChange={event => { player.current?.cancel(); setRealizationId(event.target.value); setAnswer([]); setFeedback(''); }}>{selected.realizations.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><p><strong>Actual notes:</strong> {realization.notes.join(' · ')}</p><p>{realization.displayNote} {realization.doubledDegrees.length ? `Doubled: ${realization.doubledDegrees.join(', ')}.` : ''}</p><KeyboardViewport voicing={voicing} whitePitchClasses={[0, 2, 4, 5, 7, 9, 11]} ready={ready} rangeLabel={`${realization.notes[0]}–${realization.notes.at(-1)}`} sounding={sounding}/><PlaybackControls ready={ready} state={audio.state} mode={audio.mode} onPlay={mode => {emitChordEvent('chord_audio_start',{objectId:selected.id,realizationId:realization.id,mode});void player.current?.play(voicing, mode);}} onStop={() => player.current?.cancel('Playback stopped.', 'stopped')}/><p className="ch-feedback" role="status" aria-live="polite">{audio.message}</p>
      <div className="cc-practice"><h4>Practice this reference</h4><label>Task<select value={practiceMode} onChange={event => { setPracticeMode(event.target.value as typeof practiceMode); setAnswer([]); setFeedback(''); }}><option value="formula_pitch_classes">Build formula tones</option><option value="example_pitch_classes">Build this example’s tones</option><option value="example_midi_set">Match this example’s octaves</option></select></label><div className="cc-answer" role="group" aria-label="Practice answer">{answerOptions.map(value => <button type="button" key={value} aria-pressed={answer.includes(value)} onClick={() => setAnswer(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value])}>{practiceMode === 'example_midi_set' ? value : ['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'][value]}</button>)}</div><div className="cc-practice-actions"><button className="am-button am-primary" type="button" onClick={check}>Check</button><button className="am-button am-secondary" type="button" onClick={() => { setAnswer([...expected]); setFeedback('Answer shown for this task.'); }}>Show answer</button><button className="am-button am-tertiary" type="button" onClick={() => { setAnswer([]); setFeedback(''); }}>Reset</button></div><p role="status" aria-live="polite">{feedback}</p></div>
    </article><div className="cc-index"><div className="cc-count" role="status">{filtered.length} references</div>{filtered.map(item => <article id={item.destination.split('#')[1]} className="cc-row" data-family={item.family} data-subtype={item.subtype} key={item.id}><button type="button" aria-pressed={selected.id === item.id} onClick={() => chooseObject(item.id)}><span><strong>{item.symbol}</strong><small>{item.name}</small></span><span><b>{item.definition.displayFormula.join('–')}</b><small>{item.definition.toneSpellings.join(' · ')}</small></span></button></article>)}{!filtered.length && <p>No match in this supported category.</p>}</div></div>
    <noscript><p>All {items.length} names, formulas and written-tone lists are available above. Enable JavaScript to filter, change the active preview, play sound or check practice answers.</p></noscript>
  </section>;
}
