const results=[];page.setDefaultTimeout(6500);async function check(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:String(e).slice(0,500)});}}
const base='http://127.0.0.1:4350';await page.goto(base+'/chords/finder',{waitUntil:'domcontentloaded'});
await check('multiple roots and root filter keep matching semantics',async()=>{for(const name of ['C','E','G','A'])await page.getByRole('button',{name,exact:true}).click();await expect(page.locator('[data-chord-id="c-major6"]')).toHaveCount(1);await expect(page.locator('[data-chord-id="a-m7"]')).toHaveCount(1);await page.getByLabel('Lowest note (optional)').selectOption('9');await page.getByLabel('Bass constraint').selectOption('root');await expect(page.locator('[data-chord-id="c-major6"]')).toHaveCount(0);await expect(page.locator('[data-chord-id="a-m7"]')).toHaveCount(1);});
await page.getByRole('button',{name:'Clear',exact:true}).click();
await check('supplied omission stays distinct and selects actual category object',async()=>{for(const name of ['C','D','E','G'])await page.getByRole('button',{name,exact:true}).click();await expect(page.locator('[data-chord-id="c-add9"][data-match="exact_formula"]')).toHaveCount(1);await page.locator('[data-chord-id="d-dominant11"][data-match="supplied_voicing"] a').click();await expect(page.locator('#ref-d-dominant11 button')).toHaveAttribute('aria-pressed','true');await expect(page.locator('.cc-preview h3')).toContainText('D dominant 11th');});
await check('extended user selection and history back agree',async()=>{const other=page.locator('#ref-d-dominant9 button');await other.click();await expect(other).toHaveAttribute('aria-pressed','true');await page.evaluate(()=>history.back());await expect(page.locator('#ref-d-dominant11 button')).toHaveAttribute('aria-pressed','true');});
await page.goto(base+'/chords/c-add9',{waitUntil:'domcontentloaded'});
await check('existing assisted practice remains correct',async()=>{const practice=page.locator('#practice');await practice.getByRole('button',{name:'Show answer',exact:true}).click();await practice.getByRole('button',{name:'Check answer',exact:true}).click();await page.waitForFunction(()=>window.__events.some(e=>e.name==='p0_practice_complete'&&e.properties.assisted),null,{timeout:6000});});
await page.goto(base+'/scales/c-major',{waitUntil:'domcontentloaded'});
await check('scale quiz and HTML print retain actual hand/direction',async()=>{for(const name of ['C','D','E','F','G','A','B'])await page.locator('.sc-pitch-buttons').getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('.sc-quiz-panel .sc-feedback')).toContainText('Correct');await page.getByRole('button',{name:'Print current scale',exact:true}).click();await page.emulateMedia({media:'print'});await expect(page.locator('.sc-print-only')).toBeVisible();await expect(page.locator('.sc-print-only')).toContainText('Reference edition: 2026-09-22');await page.emulateMedia({media:'screen'});await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));});
const path=artifactPath('p1-music-regression.json');await(await import('node:fs/promises')).writeFile(path,JSON.stringify(results,null,2));return {path,results};
