const fs=await import('node:fs/promises');const results=[],errors=[];page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4352/scales/c-major',{waitUntil:'domcontentloaded'});
await page.getByLabel('Tempo BPM',{exact:true}).fill('120');
await page.evaluate(()=>{window.__timeline=[];window.__watch=setInterval(()=>{const p=document.querySelector('#follow-along');window.__timeline.push({ms:performance.now(),practice:p?.getAttribute('data-practice-state'),cue:p?.querySelector('.sc-learning-head strong')?.textContent,sounding:[...document.querySelectorAll('.kn-sounding')].map(e=>+e.getAttribute('data-midi')),audio:document.querySelector('.sc-actions [role=status]')?.textContent});},30);});
await page.getByRole('button',{name:'Start practice',exact:true}).click();
await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','counting',{timeout:3000});
await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','playing',{timeout:4000});
await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','completed',{timeout:6000});
const timeline=await page.evaluate(()=>{clearInterval(window.__watch);return window.__timeline;});
assert(timeline.some(x=>x.practice==='counting'&&x.audio?.includes('Playing')));assert(!timeline.some(x=>x.practice==='preparing'&&x.audio?.includes('Playing')));
results.push({name:'audio begins during count-in, then practice advances and completes',passed:true});
await page.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','counting');
await page.getByRole('button',{name:'Pause',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','paused');
await page.getByRole('button',{name:'Resume',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','counting');
await page.getByRole('button',{name:'Stop and reset',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','idle');results.push({name:'pause/resume/reset cancel the old timeline',passed:true});
await page.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','counting');await page.getByLabel('Tempo BPM',{exact:true}).fill('80');await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','idle');
await page.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','counting');await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','idle');results.push({name:'settings and beforeprint cancel both audio and practice',passed:true});
await page.getByLabel('Scale sound',{exact:true}).uncheck();await page.getByLabel('Metronome',{exact:true}).uncheck();await page.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.locator('#follow-along')).toHaveAttribute('data-practice-state','counting');await page.getByRole('button',{name:'Stop and reset',exact:true}).click();results.push({name:'silent guide remains available',passed:true});
const path=artifactPath('audio-remediation.json');await fs.writeFile(path,JSON.stringify({results,errors,timeline},null,2));return {path,results,errors,counts:timeline.reduce((a,x)=>(a[x.practice]=(a[x.practice]||0)+1,a),{})};
