'use client';
import {useState} from 'react';
import {flushSync} from 'react-dom';
import type {ChartKey,PianoKey,StaffNote} from '@/lib/keyboard-types';
import {KeyboardDiagram} from './keyboard-diagram';
import {StaffDiagram} from './staff-diagram';
import {NotePlayback} from './tool-controls';
import {useNoteAudio} from './use-note-audio';
type Range={id:string;label:string;min_midi:number;max_midi:number};
function keysFor(notes:ChartKey[]):PianoKey[]{return notes.map(k=>({key_id:`pitch-${k.midi}`,midi:k.midi,color:k.color,default_label:k.display_names.map(n=>n.replace(/\d+$/,'')).join(' / '),label_with_octave:k.display_names.join(' / '),lookup_spellings:k.display_names,white_key_index:null,black_key_between_white_indices:null}));}
export function ChartExperience({notes,ranges,defaultNote}:{notes:ChartKey[];ranges:Range[];defaultNote:string}){
 const [rangeID,setRangeID]=useState('focus'),[clef,setClef]=useState<'both'|'treble'|'bass'>('both'),[selected,setSelected]=useState(defaultNote),[flat,setFlat]=useState(false),[error,setError]=useState(''),[snapshot,setSnapshot]=useState<{range:Range;clef:typeof clef;selected:string;flat:boolean}|null>(null);const audio=useNoteAudio();
 const range=ranges.find(r=>r.id===rangeID)!,current=notes.find(k=>k.staff_spellings.some(s=>s.name===selected))!,visible=notes.filter(k=>k.midi>=range.min_midi&&k.midi<=range.max_midi),keys=keysFor(visible);
 function pick(n:StaffNote){audio.cancel();setSelected(n.note);}function spelling(k:ChartKey,f=flat){return k.staff_spellings.find(s=>s.name===selected)??k.staff_spellings[f?k.staff_spellings.length-1:0];}
 const print=snapshot??{range,clef,selected,flat};const printKeys=notes.filter(k=>k.midi>=print.range.min_midi&&k.midi<=print.range.max_midi);const segments:ChartKey[][]=[];for(let i=0;i<printKeys.length;i+=6)segments.push(printKeys.slice(i,i+6));
 return <><section className="am-tool kn-tool kn-screen" aria-label="Staff and keyboard chart"><div className="kn-toolbar"><label className="kn-field">Displayed range<select value={rangeID} disabled={!audio.ready} onChange={e=>{audio.cancel();setRangeID(e.target.value);const r=ranges.find(r=>r.id===e.target.value)!;if(current.midi<r.min_midi||current.midi>r.max_midi)setSelected(notes.find(k=>k.midi===r.min_midi)!.display_names[0]);}}>{ranges.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><label className="kn-field">Clef<select value={clef} disabled={!audio.ready} onChange={e=>{audio.cancel();setClef(e.target.value as typeof clef);}}><option value="both">Treble and bass</option><option value="treble">Treble</option><option value="bass">Bass</option></select></label><label className="kn-checkbox"><input type="checkbox" checked={flat} disabled={!audio.ready} onChange={e=>{audio.cancel();setFlat(e.target.checked);setSelected(current.staff_spellings[e.target.checked?current.staff_spellings.length-1:0].name);}}/>Prefer flat spelling</label></div>
 <div className="kn-result" data-selected-midi={current.midi}><h2>{selected}</h2><p>{current.display_names.join(' / ')}{current.midi===60?' · Middle C':''}</p></div><p className="kn-hint">Select a note on the staff or a key below. Scroll each diagram to explore {range.label}.</p>
 {(['treble','bass'] as const).filter(c=>clef==='both'||clef===c).map(c=><div className="kn-staff-block" key={c}><h3>{c==='treble'?'Treble clef':'Bass clef'}</h3><StaffDiagram notes={visible.map(k=>spelling(k)[c])} selected={selected} onSelect={pick} ready={audio.ready}/></div>)}
 <KeyboardDiagram keys={keys} selected={current.midi} sounding={audio.sounding} ready={audio.ready} onSelect={k=>{audio.cancel();setSelected(spelling(notes.find(n=>n.midi===k.midi)! ).name);}} label={range.label}/><div className="kn-toolbar"><NotePlayback audio={audio} midi={current.midi}/><button className="am-button am-secondary" disabled={!audio.ready} onClick={()=>{audio.cancel();flushSync(()=>setSnapshot({range,clef,selected,flat}));try{window.print();}catch{setError('Printing could not start. Please use your browser’s print command.');}}}>Print current range</button></div><p role="status" className="kn-error">{error}</p><p className="kn-hint">61-key staff mode is reserved for a later release. The labeled reference already supports the verified C2–C7 layout.</p></section>
 <div className="kn-print-only" data-print-range={print.range.id} data-print-selected={print.selected}>{segments.map((segment,i)=><section className="kn-print-sheet" key={i}><div className="kn-print-title">Piano Notes Chart</div><p>{print.range.label} · {segment[0].display_names[0]}–{segment.at(-1)!.display_names[0]} · Selected: {print.selected}</p>{(['treble','bass'] as const).filter(c=>print.clef==='both'||print.clef===c).map(c=><div key={c}><h2>{c==='treble'?'Treble clef':'Bass clef'}</h2><StaffDiagram compact notes={segment.map(k=>(k.staff_spellings.find(s=>s.name===print.selected)??k.staff_spellings[print.flat?k.staff_spellings.length-1:0])[c])} selected={print.selected}/></div>)}<p>Keyboard order: {segment.map(k=>k.display_names.join(' / ')).join(' · ')}</p><KeyboardDiagram keys={keysFor(segment)} selected={notes.find(k=>k.staff_spellings.some(s=>s.name===print.selected))!.midi}/><p>Same pitch may have multiple spellings. Octave numbers are not finger numbers.</p></section>)}</div></>;
}

