'use client';
import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import type {Layout} from '@/lib/keyboard-types';
import {KeyboardDiagram} from './keyboard-diagram';
import {LayoutChoice} from './tool-controls';
export function LabeledExperience({layouts,sourceIDs}:{layouts:Layout[];sourceIDs:string[]}){
  const [layoutID,setLayoutID]=useState(layouts[0].layout_id),[octaves,setOctaves]=useState(true),[ready,setReady]=useState(false),[error,setError]=useState(''),[snapshot,setSnapshot]=useState<{layout:Layout;octaves:boolean}|null>(null);
  useEffect(()=>setReady(true),[]);const layout=layouts.find(l=>l.layout_id===layoutID)!;
  const print=snapshot??{layout,octaves};
  return <><section className="am-tool kn-tool kn-screen" aria-label="Labeled keyboard reference"><div className="kn-toolbar"><LayoutChoice layouts={layouts} value={layoutID} ready={ready} onChange={setLayoutID}/><label className="kn-checkbox"><input type="checkbox" checked={octaves} disabled={!ready} onChange={e=>setOctaves(e.target.checked)}/>Show octave numbers</label></div><p className="kn-range">{layout.label} · {layout.white_key_count} white / {layout.black_key_count} black keys</p><div className="kn-actions"><button className="am-button am-secondary" disabled={!ready} onClick={()=>{flushSync(()=>setSnapshot({layout,octaves}));try{window.print();}catch{setError('Printing could not start. Download the reference PDF instead.');}}}>Print this reference</button><a className="am-button am-tertiary" download href={`/reference/generated/keyboard-notes/labeled-${layout.key_count}-${octaves?'octaves':'letters'}.pdf`}>Download reference PDF</a></div><p role="status" className="kn-error">{error}</p><p className="kn-hint">Reference diagram—not a full-size sticker template. Octave numbers identify register, not fingers.</p><nav className="kn-actions" aria-label="Octave sections">{layout.reading_segments.map((s,i)=><a key={s.label} href={`#labels-section-${i}`} className="am-button am-tertiary">{s.label}</a>)}</nav>{layout.reading_segments.map((s,i)=><section className="kn-segment" key={s.label} id={`labels-section-${i}`} tabIndex={-1}><h2>{s.label}</h2><KeyboardDiagram keys={layout.keys.filter(k=>k.midi>=s.midi_range[0]&&k.midi<=s.midi_range[1])} octaves={octaves} label={`${s.label} labels`}/></section>)}<p>{layout.scope_note}</p></section>
  <div className="kn-print-only" data-print-layout={print.layout.layout_id} data-print-octaves={print.octaves}>{print.layout.reading_segments.map(s=><section className="kn-print-sheet" key={s.label}><div className="kn-print-title">Labeled Piano Keys</div><p>{print.layout.label} · {s.label}</p><p>Octave numbers: {print.octaves?'shown':'hidden'}. Middle C is marked C4.</p><KeyboardDiagram keys={print.layout.keys.filter(k=>k.midi>=s.midi_range[0]&&k.midi<=s.midi_range[1])} octaves={print.octaves}/><p>Sharp/flat pairs name the same key. Reference diagram—not a full-size sticker template.</p><p className="kn-print-sources">Sources: {sourceIDs.join(', ')}</p></section>)}</div></>;
}
