'use client';
import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { flushSync } from 'react-dom';
import type { CenterItem, CenterModel } from '@/lib/chord-content';
import { ReferenceAudio, type AudioStatus } from '@/lib/a-minor-audio';
import type { PlaybackMode, SearchSection } from '@/lib/a-minor-types';
import { SiteHeader, SiteFooter } from './site-chrome';
import { PlaybackControls } from './playback-controls';
import { KeyboardViewport } from './keyboard-viewport';
import { PrintVoicing } from './print-voicing';
import { PageSearch } from '../a-minor/page-search';
import { Icon } from '../a-minor/icon';
const PrintContext=createContext({ready:false,hasResults:false,printCurrent:()=>{},printFiltered:()=>{},pdf:''});
function FilterChoice({id,label,value,options,ready,onChange}:{id:string;label:string;value:string;options:{value:string|null;label:string}[];ready:boolean;onChange:(value:string)=>void}){
 const select=useRef<HTMLSelectElement>(null),[clipped,setClipped]=useState(false);
 useEffect(()=>{const el=select.current;if(!el)return;const measure=()=>{const style=getComputedStyle(el),canvas=document.createElement('canvas').getContext('2d');if(!canvas)return;canvas.font=style.font;setClipped(canvas.measureText(el.selectedOptions[0].textContent||'').width>el.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)-24);};measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect();},[value]);
 return <label htmlFor={id}>{label}<select ref={select} id={id} value={value} disabled={!ready} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value||'all'} value={o.value||''}>{o.label}</option>)}</select>{clipped&&<span className="ch-filter-value" aria-hidden="true">{options.find(o=>(o.value||'')===value)?.label}</span>}</label>;
}
export function CenterPrintActions(){const c=useContext(PrintContext);return <div className="am-section-actions"><a className="am-button am-tertiary" href={c.pdf} download><Icon name="download"/>Download original 9-chord PDF</a><button type="button" className="am-button am-secondary" disabled={!c.ready||!c.hasResults} onClick={c.printCurrent}>Print this chord</button><button type="button" className="am-button am-secondary" disabled={!c.ready||!c.hasResults} onClick={c.printFiltered}>Print matching chords</button></div>;}
type InteractiveModel=Pick<CenterModel,'items'|'filters'|'microcopy'|'whitePitchClasses'|'pdf'>;
export function ChordCenterExperience({data,heading,chartIntro,children,searchSections}:{data:InteractiveModel;heading:ReactNode;chartIntro:ReactNode;children:ReactNode;searchSections:SearchSection[]}) {
 const [root,setRoot]=useState(data.filters.defaults.root||''),[quality,setQuality]=useState(data.filters.defaults.quality||'');
 const [selected,setSelected]=useState<string|null>(data.filters.defaults.selected_chord_id);
 const [ready,setReady]=useState(false),[audio,setAudio]=useState<{state:AudioStatus;message:string;mode:PlaybackMode|null}>({state:'idle',message:'',mode:null});
 const [audioId,setAudioId]=useState<string|null>(null),[sounding,setSounding]=useState<number[]>([]),[printError,setPrintError]=useState('');
 const player=useRef<ReferenceAudio|null>(null),snapshot=useRef<CenterItem[]|null>(null),[printItems,setPrintItems]=useState<CenterItem[]|null>(null);
 const filtered=data.items.filter(i=>(!root||i.root===root)&&(!quality||i.quality===quality));
 const current=filtered.find(i=>i.id===selected)||null,currentRef=useRef<CenterItem|null>(current);currentRef.current=current;
 useEffect(()=>{const p=new ReferenceAudio((state,message,mode)=>setAudio({state,message,mode}),setSounding,data.microcopy);player.current=p;setReady(true);if(!p.available)p.cancel();const hidden=()=>{if(document.hidden){p.cancel('Playback stopped.','stopped');setAudioId(null);}};const leave=()=>p.cancel('', 'idle',false);document.addEventListener('visibilitychange',hidden);window.addEventListener('pagehide',leave);return()=>{p.dispose();player.current=null;document.removeEventListener('visibilitychange',hidden);window.removeEventListener('pagehide',leave);};},[data.microcopy]);
 useEffect(()=>{const before=()=>{player.current?.cancel();const items=snapshot.current??(currentRef.current?[currentRef.current]:[]);snapshot.current=items;flushSync(()=>setPrintItems(items));};const after=()=>{snapshot.current=null;setPrintItems(null);};window.addEventListener('beforeprint',before);window.addEventListener('afterprint',after);return()=>{window.removeEventListener('beforeprint',before);window.removeEventListener('afterprint',after);};},[]);
 function stop(){player.current?.cancel('Playback stopped.','stopped');setAudioId(null);}
 function filter(nextRoot:string,nextQuality:string){stop();setRoot(nextRoot);setQuality(nextQuality);const next=data.items.filter(i=>(!nextRoot||i.root===nextRoot)&&(!nextQuality||i.quality===nextQuality));setSelected(next.some(i=>i.id===selected)?selected:next[0]?.id||null);}
 function choose(id:string){stop();setSelected(id);}
 function play(item:CenterItem,mode:PlaybackMode){setSelected(item.id);setAudioId(item.id);void player.current?.play(item.voicing,mode);}
 function print(items:CenterItem[]){if(!items.length)return;stop();setPrintError('');snapshot.current=[...items];flushSync(()=>setPrintItems(snapshot.current));try{if(typeof window.print!=='function')throw new Error('Print unavailable');window.print();}catch{snapshot.current=null;setPrintItems(null);setPrintError(data.microcopy.print_error);}}
 return <PrintContext.Provider value={{ready,hasResults:filtered.length>0,printCurrent:()=>print(current?[current]:[]),printFiltered:()=>print(filtered),pdf:data.pdf}}><div className="am-page ch-center" data-selected-chord={selected||''} data-audio-state={audio.state} data-audio-chord={audioId||''}>
  <a className="am-skip am-screen" href="#chords-chart">Skip to chord chart</a><SiteHeader search={<PageSearch sections={searchSections} ready={ready} onOpen={stop}/>}/>
  <main id="main" className="pr-container am-screen">{heading}<section id="chords-chart" data-block-id="chords-chart" className="ch-chart" tabIndex={-1} aria-labelledby="chart-title"><h2 id="chart-title">Find a chord</h2>
  <div className="ch-filters"><FilterChoice id="center-root" label="Root note" value={root} options={data.filters.root_options} ready={ready} onChange={value=>filter(value,quality)}/><FilterChoice id="center-quality" label="Chord type" value={quality} options={data.filters.quality_options} ready={ready} onChange={value=>filter(root,value)}/><button type="button" className="am-button am-secondary" disabled={!ready||(!root&&!quality)} onClick={()=>filter('','')}>Show the full collection</button></div>
  <div className="ch-results-bar"><p role="status" aria-live="polite">{filtered.length} {filtered.length===1?'chord':'chords'}</p><button type="button" className="am-button am-secondary" disabled={!ready||!filtered.length} onClick={()=>print(filtered)}>Print matching chords</button></div>
  <p className="ch-audio-note">{data.microcopy.playback_note}</p><div role="status" aria-live="polite" className="ch-feedback">{audio.message}{printError&&<p>{printError}</p>}</div>
  {!filtered.length&&<p className="ch-empty">{data.microcopy.no_results}</p>}
  <div className="ch-results" role="group" aria-label="Chord chart results">{filtered.map(item=><section className="ch-result" data-chord-id={item.id} data-current={selected===item.id} key={item.id} aria-labelledby={`center-${item.id}-title`}><div className="ch-result-heading"><h3 id={`center-${item.id}-title`}>{item.name} <span>{item.voicing.chord_symbol}</span></h3><label className="ch-select"><input type="radio" name="center-current" checked={selected===item.id} disabled={!ready} onChange={()=>choose(item.id)}/>Current chord<span className="pr-sr-only">: {item.name}</span></label></div><div className="ch-result-notes"><strong>{item.voicing.notes_low_to_high.map(n=>n.display_pitch).join(' – ')}</strong><span>Bass: {item.voicing.bass_spelling}</span></div><KeyboardViewport voicing={item.voicing} whitePitchClasses={data.whitePitchClasses} ready={ready} rangeLabel="C3–C5" sounding={audioId===item.id?sounding:[]}/><PlaybackControls ready={ready} state={audio.state==='unavailable'?'unavailable':audioId===item.id?audio.state:'idle'} mode={audioId===item.id?audio.mode:null} onPlay={mode=>play(item,mode)} onStop={stop}/><div className="ch-result-actions"><button type="button" className="am-button am-tertiary" disabled={!ready} onClick={()=>{setSelected(item.id);print([item]);}}>Print this chord</button>{item.url&&<a className="am-button am-tertiary" href={item.url}>Notes and inversions<span className="pr-sr-only">: {item.name}</span></a>}</div></section>)}</div>
  {chartIntro}<noscript><p>JavaScript is off. All {data.items.length} diagrams, explanations, and the original nine-chord PDF remain available. Filters and sound require JavaScript.</p></noscript></section><div className="am-reading">{children}</div></main><SiteFooter url="/chords"/>
  <div className="am-print-only" id="center-print-content">{(printItems??(current?[current]:[])).map(item=><article className="ch-print-item" data-voicing-id={item.voicing.voicing_id} key={item.id}><PrintVoicing voicing={item.voicing} whitePitchClasses={data.whitePitchClasses} title={`${item.name} Piano Chord`} tones={item.tones} formula={item.formula} url="/chords" disclaimer="The marked keys show pitches, not a hand shape or a required fingering."/></article>)}{!(printItems??(current?[current]:[])).length&&<p>No matching chord to print.</p>}</div>
 </div></PrintContext.Provider>;
}
