'use client';
import { useEffect, useRef, useState } from 'react';
import { Keyboard } from '../a-minor/keyboard';
import { Icon } from '../a-minor/icon';
import type { Voicing } from '@/lib/a-minor-types';
export function KeyboardViewport({voicing,whitePitchClasses,sounding=[],ready,rangeLabel,id}:{voicing:Voicing;whitePitchClasses:number[];sounding?:number[];ready:boolean;rangeLabel:string;id?:string}) {
 const scroller=useRef<HTMLDivElement>(null),[pan,setPan]=useState({overflow:false,left:false,right:false});
 function updatePan(){const el=scroller.current;if(!el)return;const max=el.scrollWidth-el.clientWidth;setPan({overflow:max>2,left:el.scrollLeft>1,right:el.scrollLeft<max-1});}
 useEffect(()=>{const el=scroller.current;if(!el)return;const reveal=()=>{const keys=Array.from(el.querySelectorAll<HTMLElement>('.am-key.am-is-selected'));const left=Math.min(...keys.map(k=>k.offsetLeft)),right=Math.max(...keys.map(k=>k.offsetLeft+k.offsetWidth));el.scrollLeft=Math.max(0,Math.min(el.scrollWidth-el.clientWidth,(left+right)/2-el.clientWidth/2));updatePan();};reveal();const observer=new ResizeObserver(reveal);observer.observe(el);return()=>observer.disconnect();},[voicing.voicing_id]);
 return <figure className="am-figure"><div ref={scroller} className="am-keyboard-scroll" id={id} tabIndex={!ready||pan.overflow?0:-1} role="region" aria-label={`Piano keyboard, ${rangeLabel}. Use left and right arrow keys to scroll.`} onScroll={updatePan} onKeyDown={e=>{const el=scroller.current;if(!el)return;const destinations:Record<string,number>={Home:0,End:el.scrollWidth,ArrowLeft:el.scrollLeft-72,ArrowRight:el.scrollLeft+72};if(e.key in destinations){e.preventDefault();el.scrollLeft=destinations[e.key];updatePan();}}}><Keyboard voicing={voicing} whitePitchClasses={whitePitchClasses} sounding={sounding}/></div><figcaption className="am-keyboard-footer"><div className="am-keyboard-meta"><span>C4 is middle C</span><span className="am-range">{rangeLabel}</span></div><div className="am-keyboard-pan" hidden={!ready||!pan.overflow} aria-label="Keyboard view"><button type="button" className="am-pan-btn" aria-label="Show lower keys" disabled={!pan.left} onClick={()=>{if(scroller.current)scroller.current.scrollLeft-=scroller.current.clientWidth*.65;}}><Icon name="left"/></button><button type="button" className="am-pan-btn" aria-label="Show higher keys" disabled={!pan.right} onClick={()=>{if(scroller.current)scroller.current.scrollLeft+=scroller.current.clientWidth*.65;}}><Icon name="right"/></button></div></figcaption></figure>;
}
