import fs from 'node:fs';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.env.PIANO_PLAYWRIGHT_PATH||'C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.PIANO_BASE_URL||'http://127.0.0.1:3000',out=process.env.PIANO_CHECK_OUT||'docs/pianogrid-chords-content-next/09_codex-results/latest/by-key';fs.mkdirSync(out+'/screenshots',{recursive:true});
const contexts=JSON.parse(fs.readFileSync('docs/pianogrid-chords-completion/04_music/by-key.contexts.json','utf8')),seo=JSON.parse(fs.readFileSync('docs/pianogrid-chords-content-next/01_planning/url-seo-keywords.master.json','utf8')).pages.find(x=>x.url==='/chords/by-key'),merge=JSON.parse(fs.readFileSync('docs/pianogrid-chords-content-next/02_content/support.merge.json','utf8')).pages['/chords/by-key'],modules=JSON.parse(fs.readFileSync('docs/pianogrid-chords-content-next/02_content/support.modules.json','utf8'))['/chords/by-key'];
const results=[],errors=[];const check=(name,passed,detail='')=>{results.push({name,passed:Boolean(passed),detail});if(!passed)console.error('FAIL',name,detail)};const clean=s=>(s||'').replaceAll('’',"'").replaceAll('–','-').replace(/\s+/g,' ').trim();
check('Prepared completion data has 24 contexts and 336 rows',contexts.length===24&&contexts.every(x=>x.rows.length===14)&&contexts.reduce((n,x)=>n+x.rows.length,0)===336);check('Each context separates seven triads and seven sevenths',contexts.every(x=>x.rows.filter(r=>['major','minor','diminished'].includes(r.quality)).length===7&&x.rows.filter(r=>['major7','minor7','dominant7','halfDiminished7'].includes(r.quality)).length===7));check('Prepared data has no fingering field or claim',contexts.every(x=>x.rows.every(r=>!('fingering' in r))));
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const nojs=await browser.newPage({javaScriptEnabled:false,viewport:{width:1440,height:900}});const response=await nojs.goto(base+'/chords/by-key'),raw=await response.text(),body=clean(await nojs.locator('body').textContent());fs.writeFileSync(out+'/by-key-raw.html',raw);check('HTTP 200 and planned TDK/H1/canonical',response.status()===200&&(await nojs.title()).includes('Piano')&&Boolean(await nojs.locator('meta[name=description]').getAttribute('content'))&&await nojs.locator('link[rel=canonical]').getAttribute('href')==='https://pianogrid.com/chords/by-key'&&Boolean(clean(await nojs.locator('h1').innerText())));check('No meta keywords',await nojs.locator('meta[name=keywords]').count()===0);check('SSR exposes 24 contexts and all 336 rows',await nojs.locator('.bk-key-panel').count()===24&&await nojs.locator('.bk-key-panel[hidden]').count()===0&&await nojs.locator('.bk-table-scroll tbody tr').count()===336&&(raw.match(/data-degree=/g)||[]).length===336);check('Key root quality and Roman numeral stay separate',JSON.stringify(await nojs.locator('.bk-terms dt').allTextContents())===JSON.stringify(['Key','Root note','Chord quality','Roman numeral']));check('Original content remains',merge.blocks.every(x=>body.includes(clean(x.heading))&&body.includes(clean(x.body))));const supplemental=modules.supplemental_blocks.flatMap(x=>[x.content.heading,...x.content.paragraphs,...x.content.steps,...(x.content.table?.rows.flat()||[])]);check('Current by-key instructions replace outdated scope',body.includes('The current tables cover 12 major and 12 natural-minor keys')&&!body.includes('current major/minor detail template cannot render it')&&body.includes('B diminished has its own detail page'));
 for(const ctx of contexts){const label=ctx.tonic+' '+(ctx.mode==='major'?'major':'natural minor'),panel=nojs.locator('.bk-key-panel').filter({has:nojs.locator('h3',{hasText:label+' chords'})});check(label+' SSR rows',await panel.count()===1&&await panel.locator('tbody tr').count()===14);}const hrefs=await nojs.locator('main a[href]').evaluateAll(ns=>ns.map(n=>n.getAttribute('href')));check('Required support links are present',['/chords','/chord-progressions'].every(x=>hrefs.includes(x)));check('No duplicate IDs',await nojs.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return ids.length===new Set(ids).size}));for(const href of [...new Set(hrefs.filter(x=>x?.startsWith('/')).map(x=>x.split('#')[0]))])check('Linked target '+href+' returns 200',(await nojs.request.get(base+href)).status()===200,href);await nojs.close();
 const page=await browser.newPage({viewport:{width:1440,height:950}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(base+'/chords/by-key');await page.waitForFunction(()=>document.querySelectorAll('.bk-key-panel:not([hidden])').length===1);const select=page.getByLabel('Key',{exact:true}),values=await select.locator('option').evaluateAll(ns=>ns.map(n=>n.value));check('Interactive picker exposes all 24 contexts',values.length===24,values);for(const value of values){await select.selectOption(value);check('Selection '+value+' shows one 14-row table',await page.locator('.bk-key-panel:visible').count()===1&&await page.locator('.bk-key-panel:visible tbody tr').count()===14);}await select.selectOption('C major');await page.setViewportSize({width:1440,height:950});await page.screenshot({path:out+'/screenshots/by-key-1440-c-major.png',fullPage:true});for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});check('Responsive width '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth})));}await select.selectOption(values.find(x=>x==='D natural minor')||values[14]);await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/screenshots/by-key-390-minor.png',fullPage:true});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.waitForTimeout(100);check('200% text reflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth})));check('No runtime or hydration errors',errors.length===0,errors);const xml=await(await page.request.get(base+'/sitemap.xml')).text();check('Current sitemap and includes by-key/completion categories',(xml.match(/<loc>/g)||[]).length>0&&['/chords/by-key','/chords/extended','/chords/altered'].every(x=>xml.includes('https://pianogrid.com'+x+'</loc>')));await page.close();
}catch(error){check('By-key browser runner completed',false,error.stack)}finally{await browser.close()}
const report={executed_at:new Date().toISOString(),base,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,counts:{contexts:24,rows:336,sitemap:173},results,not_tested:['real mobile/tablet device','screen reader','independent music-theory review']};fs.writeFileSync(out+'/validation.json',JSON.stringify(report,null,2)+'\n');console.log('By-key: '+report.passed+' passed, '+report.failed+' failed');process.exitCode=report.failed?1:0;
