from pathlib import Path
from playwright.sync_api import sync_playwright
import json, time
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
checks=[]; errors=[]
def record(name,passed,details=None):
 checks.append({'name':name,'passed':bool(passed),'details':details})
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 ver=browser.version
 page=browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
 page.on('pageerror',lambda e:errors.append(str(e)))
 requests=[];page.on('request',lambda req:requests.append(req.url))
 page.set_content((ROOT/'index.html').read_text(),wait_until='load');page.wait_for_timeout(1000)
 state=page.evaluate('PianoLabPreview.getState()')
 record('audio_not_initialized_on_load',state['audioCreated'] is False,state)
 record('no_external_requests',not any(u.startswith(('http:','https:')) for u in requests),requests)
 record('single_h1',page.locator('h1').count()==1)
 record('preview_noindex',page.locator('meta[name="robots"]').get_attribute('content')=='noindex,nofollow')
 record('no_sheet_music_navigation',page.locator('a[href="/sheet-music"]').count()==0)
 record('no_account_or_paid_feature_claims',not any(s in page.locator('body').inner_text() for s in ['Sign in','1,000+','Start Practicing','MIDI connected','Subscribe now']))
 record('piano_sequence_desktop',page.locator('.desktop-keyboard [data-midi]').count()==24)
 record('piano_sequence_mobile',page.locator('.mobile-keyboard [data-midi]').count()==13)
 page.evaluate('PianoLabPreview.capture()')
 page.screenshot(path=str(ROOT/'design/desktop-1440.png'),full_page=True)
 page.screenshot(path=str(ROOT/'design/desktop-hero.png'),clip={'x':0,'y':0,'width':1440,'height':950})
 dims=[]
 for width in [320,360,390,600,768,800,1024,1440,1920]:
  page.set_viewport_size({'width':width,'height':1000})
  page.wait_for_timeout(70)
  result=page.evaluate('({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,h1:document.querySelector("h1").getBoundingClientRect().toJSON()})')
  dims.append({'width':width,**result})
 record('responsive_no_horizontal_overflow',all(d['scroll']<=d['client'] for d in dims),dims)
 page.set_viewport_size({'width':390,'height':844});page.evaluate('PianoLabPreview.capture()');page.screenshot(path=str(ROOT/'design/mobile-390.png'),full_page=True)
 page.screenshot(path=str(ROOT/'design/mobile-hero.png'))
 page.locator('.menu-button').click()
 record('mobile_menu_opens',page.locator('#mobile-nav').is_visible())
 page.keyboard.press('Escape')
 record('mobile_menu_closes_on_escape',not page.locator('#mobile-nav').is_visible())
 page.locator('.hero-actions .button-primary').click();page.wait_for_timeout(800)
 pos=page.locator('#explore').bounding_box()
 record('primary_cta_scrolls_to_tasks',pos is not None and 40<pos['y']<160,pos)
 page.locator('.task[data-route="/chords"]').click()
 record('route_preview_works',page.locator('#route-dialog').is_visible() and page.locator('#dialog-route').inner_text()=='/chords')
 page.keyboard.press('Escape')
 record('dialog_closes_on_escape',not page.locator('#route-dialog').is_visible())
 record('dialog_focus_restored',page.evaluate('document.activeElement.dataset.route')=='/chords')
 page.locator('[data-chord="a"]').click()
 record('major_toggle_updates_notes',page.locator('#third-letter').inner_text()=='C♯' and page.locator('#interval-left').inner_text()=='4 semitones')
 page.locator('#study-play').click();page.wait_for_timeout(180)
 st=page.evaluate('PianoLabPreview.getState()')
 record('user_gesture_initializes_audio',st['audioCreated'] and st['audioState']=='running',st)
 record('major_audio_correct_midi',[x['midi'] for x in st['notesScheduled'][-3:]]==[57,61,64])
 page.wait_for_timeout(1750)
 record('audio_nodes_cleaned_up',page.evaluate('PianoLabPreview.getState().activeOscillators')==0)
 page.locator('[data-chord="am"]').click();page.locator('#study-play').click();page.wait_for_timeout(150)
 st=page.evaluate('PianoLabPreview.getState()')
 record('minor_audio_correct_midi',[x['midi'] for x in st['notesScheduled'][-3:]]==[57,60,64])
 page.evaluate('window.scrollTo(0,0)');page.wait_for_timeout(300)
 page.locator('.mobile-keyboard .piano-key[data-midi="57"]').focus();page.keyboard.press('ArrowRight')
 record('keyboard_arrow_moves_by_semitone',page.evaluate('document.activeElement.dataset.midi')=='58')
 page.keyboard.press('Enter');page.wait_for_timeout(120)
 record('keyboard_enter_schedules_pitch',page.evaluate('PianoLabPreview.getState().notesScheduled.at(-1).midi')==58)
 page.emulate_media(reduced_motion='reduce');page.wait_for_timeout(150)
 st=page.evaluate('PianoLabPreview.getState()')
 record('reduced_motion_static',st['motion']=='reduced_motion_static' and page.locator('.motion-button').is_disabled(),st)
 page.emulate_media(reduced_motion='no-preference');page.evaluate('PianoLabPreview.restore()');page.wait_for_timeout(300)
 page.locator('.motion-button').click()
 record('motion_pause_works',page.evaluate('PianoLabPreview.getState().paused') is True)
 page.locator('.motion-button').click();page.locator('#resources').scroll_into_view_if_needed();page.wait_for_timeout(250)
 record('offscreen_motion_stops',page.evaluate('PianoLabPreview.getState().visible') is False)
 # Ensure every original destination anchor is represented in the preview map.
 mapping=page.evaluate('JSON.parse(document.querySelector("#site-config").textContent).destinations')
 links=page.locator('[data-route]').evaluate_all('(els)=>els.map(e=>e.dataset.route)')
 record('all_route_previews_have_content',all(u in mapping for u in links),sorted(set(links)))
 record('no_browser_exceptions',not errors,errors)
 # Desktop frozen restored for supplemental screenshots.
 page.set_viewport_size({'width':1440,'height':950});page.evaluate('document.documentElement.style.scrollBehavior="auto";window.scrollTo(0,0);PianoLabPreview.capture()');page.wait_for_timeout(400)
 # Crop the original top-of-page capture; interaction tests may leave focus scrolled.
 Image.open(ROOT/'design/desktop-1440.png').crop((0,0,1440,950)).save(ROOT/'design/desktop-hero.png')
 # JS-disabled and reduced-motion fallback check.
 ctx=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844})
 nojs=ctx.new_page();nojs.set_content((ROOT/'index.html').read_text(),wait_until='load')
 record('no_js_headline_and_links_visible',nojs.locator('h1').is_visible() and nojs.locator('.hero-actions a').count()==2 and nojs.locator('.task').count()==6)
 ctx.close();browser.close()
report={'date':'2026-09-10','browser':'Chromium '+ver,'environment':'Linux headless, device viewport emulation; not physical Windows/iPhone testing','status':'PASS' if all(x['passed'] for x in checks) else 'NEEDS_FIX','passed':sum(x['passed'] for x in checks),'failed':sum(not x['passed'] for x in checks),'checks':checks,'not_tested':['Physical iPhone/Safari or Windows device','Human listening / piano timbre approval','Screen-reader testing with NVDA or VoiceOver','Existing Next.js repository build and production routes','Trademark clearance, registrability, domain availability','Live Core Web Vitals or search indexing','Independent third-party acceptance']}
(ROOT/'qa/report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps({'status':report['status'],'passed':report['passed'],'failed':report['failed'],'failures':[c for c in checks if not c['passed']]},ensure_ascii=False,indent=2))
