'use client';
import {useEffect,useRef} from 'react';
import type {StaffNote} from '@/lib/keyboard-types';
export function StaffDiagram({notes,selected,onSelect,ready=true,compact=false}:{notes:StaffNote[];selected:string;onSelect?:(n:StaffNote)=>void;ready?:boolean;compact?:boolean}){
 const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const center=()=>{const el=ref.current?.querySelector<SVGElement>('[aria-pressed="true"]');if(el&&ref.current){const b=el.getBoundingClientRect(),a=ref.current.getBoundingClientRect();ref.current.scrollLeft+=b.left-a.left-ref.current.clientWidth/2+b.width/2;}};center();const observer=new ResizeObserver(center);if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[selected,notes]);
 if(!notes.length)return null;const min=Math.min(-4,...notes.map(n=>n.staff_step_from_bottom_line)),max=Math.max(10,...notes.map(n=>n.staff_step_from_bottom_line)),gap=compact?6:7,bottom=40+max*gap,height=70+(max-min)*gap,width=84+notes.length*76,y=(step:number)=>bottom-step*gap,clef=notes[0].clef;
 return <div className="kn-staff-frame"><svg className="kn-clef-anchor" width="64" height={height} viewBox={`0 0 64 ${height}`} aria-hidden="true">{[0,2,4,6,8].map(s=><line key={s} x1="0" x2="64" y1={y(s)} y2={y(s)} stroke="currentColor"/>)}<text x="8" y={y(clef==='treble'?2:6)+(clef==='treble'?12:29)} fontSize="64" className="kn-clef">{clef==='treble'?'𝄞':'𝄢'}</text></svg><div className="kn-staff-scroll" ref={ref} role="region" tabIndex={0} aria-label={`${clef} staff notes`}><svg className="kn-staff" width={width} height={height} viewBox={`0 0 ${width} ${height}`} role="group" aria-label={`${clef} clef: ${notes[0].note} to ${notes.at(-1)!.note}`}>
 {[0,2,4,6,8].map(s=><line key={s} x1="12" x2={width-8} y1={y(s)} y2={y(s)} stroke="currentColor" strokeWidth="1"/>)}
 <text x="18" y={y(clef==='treble'?2:6)+(clef==='treble'?12:29)} fontSize="64" className="kn-clef kn-inline-clef" aria-hidden="true">{clef==='treble'?'𝄞':'𝄢'}</text>
 {notes.map((n,i)=>{const x=84+i*76,active=n.note===selected,accidental=n.accidental?.replaceAll('#','♯').replaceAll('b','♭');return <g key={`${n.note}-${i}`} role={onSelect?'button':'img'} tabIndex={onSelect&&ready?0:undefined} aria-disabled={onSelect&&!ready?true:undefined} aria-label={`${n.note}, ${clef} clef`} aria-pressed={onSelect?active:undefined} data-note={n.note} data-midi={n.midi} data-step={n.staff_step_from_bottom_line} onClick={()=>ready&&onSelect?.(n)} onKeyDown={e=>{if(onSelect&&ready&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onSelect(n);}}} className={active?'kn-staff-note kn-active':'kn-staff-note'}>
 <rect x={x-32} y="4" width="66" height={height-8} rx="4" fill="transparent" className="kn-note-hit"/>{n.ledger_line_steps.map(s=><line key={s} data-ledger={s} x1={x-15} x2={x+15} y1={y(s)} y2={y(s)} stroke="currentColor" strokeWidth="1.5"/>)}{accidental&&<text x={x-(accidental.length>1?37:29)} y={y(n.staff_step_from_bottom_line)+6} fontSize="22">{accidental}</text>}<ellipse cx={x} cy={y(n.staff_step_from_bottom_line)} rx="8" ry="5.5" transform={`rotate(-15 ${x} ${y(n.staff_step_from_bottom_line)})`} fill="currentColor"/>{active&&<circle cx={x} cy={y(n.staff_step_from_bottom_line)} r="13" fill="none" stroke="currentColor" strokeWidth="2"/>}<text x={x} y={height-9} textAnchor="middle" fontSize="14">{n.note}</text></g>;})}</svg></div></div>;
}

